Repository kubernetes-sigs/kind, pull requests merged in 2018-12, with the labels that each got.

#146 hotfix: add conntrack to base image
  hack/build/push-base.sh
  hack/build/push-node.sh
  images/base/Dockerfile
  pkg/build/base/sources/images_sources.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/S

#149 Include cluster name in export command after creation
  pkg/cluster/context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#150 point to #kind instead of #sig-testing
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#141 Add flag to Wait for node to reach ready state
  cmd/kind/create/cluster/createcluster.go
  docs/user/user-guide.md
  pkg/cluster/context.go
  pkg/cluster/nodes/nodes.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#145 Enhance user guide
  README.md
  docs/README.md
  docs/user/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L

#158 Fix broken links
  images/node/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#159 enable --wait and increase loglevel for e2e
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#157 kubeadm: support v1beta1 and add all config objects
  pkg/cluster/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#160 add neolit123 to reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#162 fixes command for building from source
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, priority/important-longterm, size/XS

#167 Fix links to base/node images and advanced building instructions.
  docs/user/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, priority/important-longterm, size/XS

#165 Add system requirements for macos/windows
  docs/user/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#173 README.md: invite reaching out
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#179 upgrade to v1.12.3
  pkg/cluster/config/v1alpha1/default.go
  pkg/cluster/config/v1alpha2/default.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/XS

#184 Cleanup the generated kube config
  pkg/cluster/context.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#187 Adding some meta information to the 2 contexts for Create
  pkg/cluster/context.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#190 fix kustomize integration on windows
  pkg/kustomize/kustomize.go
Labels: approved, cncf-cla: yes, lgtm, size/S
