Repository kubernetes-sigs/kind, pull requests merged in 2018-11, with the labels that each got.

#89 Improve Performance
  Gopkg.lock
  hack/verify-generated.sh
  images/base/Dockerfile
  images/base/clean-install
  pkg/build/base/sources/images_sources.go
  pkg/build/kube/bits.go
  pkg/build/node/node.go
  pkg/cluster/cluster.go
  pkg/cluster/node.go
  pkg/docker/archive.go
  pkg/docker/doc.go
  pkg/docker/docker.go
  pkg/log/fidget/spinner.go
  pkg/log/status.go
  vendor/github.com/briandowns/spinner/LICENSE
  vendor/github.com/briandowns/spinner/character_sets.go
  vendor/github.com/briandowns/spinner/spinner.go
  vendor/github.com/fatih/color/LICENSE.md
  vendor/github.com/fatih/color/color.go
  vendor/github.com/fatih/color/doc.go
  vendor/github.com/mattn/go-colorable/LICENSE
  vendor/github.com/mattn/go-colorable/colorable_appengine.go
  vendor/github.com/mattn/go-colorable/colorable_others.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-colorable/noncolorable.go
  vendor/github.com/mattn/go-isatty/LICENSE
  vendor/github.com/mattn/go-isatty/doc.go
  vendor/github.com/mattn/go-isatty/isatty_appengine.go
  vendor/github.com/mattn/go-isatty/isatty_bsd.go
  vendor/github.com/mattn/go-isatty/isatty_linux.go
  vendor/github.com/mattn/go-isatty/isatty_linux_ppc64x.go
  vendor/github.com/mattn/go-isatty/isatty_others.go
  vendor/github.com/mattn/go-isatty/isatty_solaris.go
  vendor/github.com/mattn/go-isatty/isatty_windows.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#90 upgrade default images
  hack/build/push-node.sh
  pkg/build/node/node.go
  pkg/cluster/config/default.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#91 add a diagram
  docs/design.md
  docs/images/diagram.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#93 fix timeout bug
  pkg/cluster/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#95 Config cleanup
  docs/kind-example-config.yaml
  pkg/cluster/cluster.go
  pkg/cluster/config/default.go
  pkg/cluster/config/encoding/encoding_test.go
  pkg/cluster/config/types.go
  pkg/cluster/config/validate.go
  pkg/cluster/config/validate_test.go
  pkg/cluster/config/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#96 switch to yaml.UnmarshallStrict for config
  Gopkg.lock
  pkg/cluster/config/encoding/encoding.go
  vendor/sigs.k8s.io/yaml/LICENSE
  vendor/sigs.k8s.io/yaml/fields.go
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_go110.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XL

#98 cmd/kind: add new line after stderr errors
  cmd/kind/kind.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/backlog, size/XS

#97 pkg/cluster: trim the sha digest when showing status
  pkg/cluster/cluster.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/backlog, size/XS

#100 Fix typos: unkown -> unknown
  pkg/cluster/node.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#101 Fix broken links
  docs/design.md
  images/node/README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#102 refactoring: convert exec.Cmd to an interface, break node logic into …
  pkg/build/base/base.go
  pkg/build/kube/bazelbuildbits.go
  pkg/build/kube/dockerbuildbits.go
  pkg/build/kube/version.go
  pkg/build/node/node.go
  pkg/cluster/cluster.go
  pkg/cluster/consts/consts.go
  pkg/cluster/nodes/node.go
  pkg/docker/docker.go
  pkg/exec/exec.go
  pkg/exec/local.go
  pkg/log/status.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#104 Fix build node-image cmd and add user docs
  README.md
  cmd/kind/build/baseimage/baseimage.go
  cmd/kind/build/build.go
  cmd/kind/build/nodeimage/nodeimage.go
  docs/README.md
  docs/user-guide.md
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, kind/bug, kind/documentation, lgtm, ok-to-test, size/M

#106 More code cleanup
  pkg/cluster/cluster.go
  pkg/cluster/nodes/create.go
  pkg/cluster/nodes/doc.go
  pkg/cluster/nodes/node.go
  pkg/cluster/nodes/nodes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#108 clean up pkg/cluster/config
  pkg/cluster/config/default.go
  pkg/cluster/config/doc.go
  pkg/cluster/config/register.go
  pkg/cluster/config/types.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#121 minor repo cleanup
  .gitignore
  hack/boilerplate.go.txt
  hack/update-generated.sh
  main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#127 Update sample kind config file
  docs/kind-example-config.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#129 ensure consistent ownership of the image tarballs
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#123 add `kind export logs`
  cmd/kind/create/cluster/createcluster.go
  cmd/kind/export/export.go
  cmd/kind/export/logs/logs.go
  cmd/kind/kind.go
  docs/todo.md
  hack/ci/e2e.sh
  pkg/cluster/context.go
  pkg/cluster/logs/doc.go
  pkg/cluster/logs/logs.go
  pkg/cluster/nodes/nodes.go
  pkg/docker/cp.go
  pkg/util/errors.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#74 Add a debug flag to retain the broken nodes for debugging.
  cmd/kind/create/cluster/createcluster.go
  cmd/kind/delete/cluster/deletecluster.go
  cmd/kind/export/logs/logs.go
  cmd/kind/get/kubeconfigpath/kubeconfigpath.go
  pkg/cluster/clusters.go
  pkg/cluster/context.go
  pkg/cluster/context_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#139 clean up context, flag structs, and runE
  cmd/kind/build/baseimage/baseimage.go
  cmd/kind/build/nodeimage/nodeimage.go
  cmd/kind/create/cluster/createcluster.go
  cmd/kind/delete/cluster/deletecluster.go
  cmd/kind/export/logs/logs.go
  cmd/kind/get/kubeconfigpath/kubeconfigpath.go
  hack/ci/e2e.sh
  pkg/cluster/clusters.go
  pkg/cluster/context.go
  pkg/cluster/context_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ¯\_(ツ)_/¯

#128 Add dev guide
  README.md
  docs/README.md
  docs/design/README.md
  docs/design/base-image.md
  docs/design/design.md
  docs/design/node-image.md
  docs/design/overview.md
  docs/devel/README.md
  docs/user/kind-example-config.yaml
  docs/user/user-guide.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L

#140 add a version command and initial release
  cmd/kind/kind.go
  cmd/kind/version/version.go
  hack/build/cross.sh
  hack/release/create.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#142 don't tag the commit after the release
  hack/release/create.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#144 Fix diagram image in design doc
  docs/design/design.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
