Repository kubernetes-sigs/kind, pull requests merged in 2018-10, with the labels that each got.

#50 upgrade systemd
  images/base/Dockerfile
  pkg/build/base/sources/images_sources.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#51 clean up docker run
  pkg/build/node/node.go
  pkg/cluster/node.go
  pkg/docker/docker.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#54 correct docker.Run error handling
  pkg/docker/docker.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#59 switch cli to kind verb noun
  README.md
  cmd/kind/build/baseimage/baseimage.go
  cmd/kind/build/build.go
  cmd/kind/build/nodeimage/nodeimage.go
  cmd/kind/create/cluster/createcluster.go
  cmd/kind/create/create.go
  cmd/kind/delete/cluster/deletecluster.go
  cmd/kind/delete/delete.go
  cmd/kind/kind.go
  docs/node-image.md
  docs/todo.md
  hack/build/push-base.sh
  hack/build/push-node.sh
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#60 use a volume instead of specifically tmpfs for docker graph
  images/base/Dockerfile
  pkg/build/base/sources/images_sources.go
  pkg/build/node/node.go
  pkg/cluster/cluster.go
  pkg/cluster/node.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#66 pin default node image to the sha
  pkg/cluster/config/default.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#69 Add status tracking with loading spinners, clean up logging
  Gopkg.lock
  README.md
  cmd/kind/build/build.go
  cmd/kind/kind.go
  pkg/cluster/cluster.go
  pkg/cluster/node.go
  pkg/log/status.go
  pkg/log/util.go
  vendor/github.com/briandowns/spinner/LICENSE
  vendor/github.com/briandowns/spinner/character_sets.go
  vendor/github.com/briandowns/spinner/spinner.go
  vendor/github.com/fatih/color/LICENSE.md
  vendor/github.com/fatih/color/color.go
  vendor/github.com/fatih/color/doc.go
  vendor/github.com/mattn/go-colorable/LICENSE
  vendor/github.com/mattn/go-colorable/colorable_appengine.go
  vendor/github.com/mattn/go-colorable/colorable_others.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-colorable/noncolorable.go
  vendor/github.com/mattn/go-isatty/LICENSE
  vendor/github.com/mattn/go-isatty/doc.go
  vendor/github.com/mattn/go-isatty/isatty_appengine.go
  vendor/github.com/mattn/go-isatty/isatty_bsd.go
  vendor/github.com/mattn/go-isatty/isatty_linux.go
  vendor/github.com/mattn/go-isatty/isatty_linux_ppc64x.go
  vendor/github.com/mattn/go-isatty/isatty_others.go
  vendor/github.com/mattn/go-isatty/isatty_solaris.go
  vendor/github.com/mattn/go-isatty/isatty_windows.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#75 add `kind get kubeconfig-path`
  cmd/kind/get/get.go
  cmd/kind/get/kubeconfigpath/kubeconfigpath.go
  cmd/kind/kind.go
  pkg/cluster/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#68 explicitly set the API server to a random port
  pkg/cluster/cluster.go
  pkg/cluster/kubeadm/config.go
  pkg/cluster/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#83 switch spinner library to patched copy
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/briandowns/spinner/spinner.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#86 Fix link to issues in readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#87 remove spinner constraint
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS
