Repository kubernetes-sigs/kind, pull requests merged in 2018-09, with the labels that each got.

#8 improve docs slightly
  README.md
  docs/README.md
  images/base/README.md
  images/node/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#12 chmod +x ./hack/ci/e2e.sh
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#11 update build badge to point to CI build job
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#15 fix symlink handling
  pkg/build/base/base.go
  pkg/cluster/node.go
  pkg/fs/fs.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/S

#16 eliminate test-infra from docker labels and hack scripts
  hack/ci/e2e.sh
  pkg/build/node/node.go
  pkg/cluster/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#18 add demo
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#19 fix node build with prebuilt base image
  hack/ci/e2e.sh
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#20 explicitly use an infinite sleep to keep the node build container
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#24 image pull fixes
  hack/ci/e2e.sh
  pkg/build/node/node.go
  pkg/docker/docker.go
  pkg/exec/exec.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#25 handle entrypoint more explicitly at runtime
  images/base/Dockerfile
  pkg/build/base/sources/images_sources.go
  pkg/cluster/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#27 Add default storage class
  pkg/cluster/cluster.go
  pkg/cluster/const.go
  pkg/cluster/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#31 move COC so github will recognize it
  CODE_OF_CONDUCT.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#35 Reduce base image size.
  images/base/Dockerfile
  pkg/build/base/sources/images_sources.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#37 drop --tag flags
  cmd/kind/build/base/base.go
  cmd/kind/build/node/node.go
  hack/build/push-base.sh
  hack/build/push-node.sh
  pkg/build/base/base.go
  pkg/build/node/node.go
  pkg/docker/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#40 make some mounts shared
  images/base/Dockerfile
  pkg/build/base/sources/images_sources.go
  pkg/cluster/cluster.go
  pkg/cluster/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#41 add image pull retries
  pkg/build/node/node.go
  pkg/cluster/cluster.go
  pkg/cluster/node.go
  pkg/docker/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#44 don't delete the nodes when kubeadm init fails so we can debug them
  pkg/cluster/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#45 add nsswitch work around
  pkg/cluster/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#46 add means to handle different kubeadm APIs
  Gopkg.lock
  Gopkg.toml
  pkg/cluster/kubeadm/config.go
  vendor/k8s.io/apimachinery/LICENSE
  vendor/k8s.io/apimachinery/pkg/util/version/doc.go
  vendor/k8s.io/apimachinery/pkg/util/version/version.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#47 hack: include all update* calls in update-all.sh
  hack/update-all.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS
