Repository kubernetes-sigs/kind, pull requests merged in 2019-06, with the labels that each got.

#582 release: use correct exit code
  hack/release/create.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#585 use our own systemd units and restart kubelet more often
  cmd/kind/build/nodeimage/nodeimage.go
  pkg/build/kube/aptbits.go
  pkg/build/kube/bazelbuildbits.go
  pkg/build/kube/dockerbuildbits.go
  pkg/build/node/cni.go
  pkg/build/node/node.go
  pkg/build/node/systemd.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#587 Kindnet: wait until podCIDR
  cmd/kindnetd/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#580 Add support for kubeadm v1beta2 config
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#572 Document how to enable feature gates
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#584 Add shellcheck verification
  hack/.shellcheck_failures
  hack/verify-all.sh
  hack/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#590 remove unnecessary comment from dockerfile
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#591 eliminate shellcheck failures
  hack/.shellcheck_failures
  hack/util/goarch.sh
  hack/util/goos.sh
  hack/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#593 Export logs and load images only on Internal nodes
  cmd/kind/load/docker-image/docker-image.go
  cmd/kind/load/image-archive/image-archive.go
  pkg/cluster/context.go
  pkg/cluster/internal/context/context.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#596 Minor tooling improvements
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify-shellcheck.sh
  hack/verify-spelling.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#545 kindnet 0.2.0
  cmd/kindnetd/go.mod
  cmd/kindnetd/go.sum
  cmd/kindnetd/main.go
  images/kindnetd/Dockerfile
  images/kindnetd/VERSION
  pkg/build/node/cni.go
  pkg/cluster/internal/create/actions/installcni/cni.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#601 Cleanup hack scripts.
  .gitignore
  hack/update/all.sh
  hack/update/deps.sh
  hack/update/generated.sh
  hack/update/gofmt.sh
  hack/verify-all.sh
  hack/verify/all.sh
  hack/verify/generated.sh
  hack/verify/gofmt.sh
  hack/verify/golint.sh
  hack/verify/govet.sh
  hack/verify/shellcheck.sh
  hack/verify/spelling.sh
  hack/verify/staticcheck.sh
  site/content/docs/contributing/project-structure.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#603 refactor kindnetd
  cmd/kindnetd/cni.go
  cmd/kindnetd/main.go
  cmd/kindnetd/masq.go
  cmd/kindnetd/routes.go
  images/kindnetd/VERSION
  pkg/build/node/cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#604 Remove verify-all script.
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#605 slightly improve hack/ organization and docs
  hack/ci/README.md
  hack/release/build/README.md
  hack/release/build/cross.sh
  hack/release/build/ctr/README.md
  hack/release/build/ctr/cloudbuild.yaml
  hack/release/build/ctr/run.sh
  hack/release/build/push-base.sh
  hack/release/build/push-node.sh
  hack/release/create.sh
  hack/tools/README.md
  hack/update/README.md
  hack/util/README.md
  hack/util/goarch.sh
  hack/util/goinstalldir.sh
  hack/util/goos.sh
  hack/verify/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#608 prevent hang in log export
  pkg/exec/exec.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#478 Add option to print raw kubeconfig
  cmd/kind/get/get.go
  cmd/kind/get/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#610 nit kind get kubeconfig
  cmd/kind/get/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#609 small correctness fix
  pkg/exec/exec.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#617 Pull and save Docker images in parallel
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#624 Warn if cluster name is too long.
  pkg/cluster/internal/create/create.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#615 add a workaround to a Docker (aufs) bug
  images/base/entrypoint
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#627 upgrade to go 1.12.6
  Makefile
  README.md
  images/kindnetd/Dockerfile
  site/content/docs/contributing/getting-started.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#629 refactor build tooling
  Makefile
  hack/build/README.md
  hack/build/go_container.sh
  hack/build/goarch.sh
  hack/build/goinstalldir.sh
  hack/build/goos.sh
  hack/util/README.md
  images/kindnetd/Dockerfile
  images/kindnetd/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#632 Use config file to join nodes to the cluster [fixed]
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/create/actions/kubeadmjoin/join.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/cluster/nodes/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#618 Add kubectl version issue to known-issues.md
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#636 Initial IPv6 support
  hack/ci/e2e.sh
  pkg/cluster/config/default.go
  pkg/cluster/config/fuzzer/fuzzer.go
  pkg/cluster/config/types.go
  pkg/cluster/config/v1alpha3/default.go
  pkg/cluster/config/v1alpha3/types.go
  pkg/cluster/config/v1alpha3/zz_generated.conversion.go
  pkg/cluster/config/validate.go
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/create/actions/loadbalancer/loadbalancer.go
  pkg/cluster/internal/create/nodes.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/cluster/internal/loadbalancer/config.go
  pkg/cluster/nodes/create.go
  pkg/cluster/nodes/node.go
  pkg/cluster/nodes/util.go
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#641 Change CNI daemonset api version
  pkg/build/node/cni.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#642 Quote ControlPlaneEndpoint for kubeadm v1beta1
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#645 switch external loadbalancer back to haproxy, health check
  images/haproxy/Dockerfile
  images/haproxy/haproxy.cfg
  images/haproxy/push-cross.sh
  pkg/cluster/internal/loadbalancer/config.go
  pkg/cluster/internal/loadbalancer/const.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#628 Automatically add the docker network to no_proxy
  images/base/entrypoint
  pkg/cluster/nodes/create.go
  pkg/cluster/nodes/node.go
  pkg/container/docker/network.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#633 make CNI ipv6 route optional
  cmd/kindnetd/cni.go
  cmd/kindnetd/main.go
  cmd/kindnetd/util.go
  images/kindnetd/VERSION
  pkg/build/node/cni.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#382 load image only if not present
  cmd/kind/load/docker-image/docker-image.go
  cmd/kind/load/image-archive/image-archive.go
  pkg/cluster/nodes/node.go
  pkg/container/docker/image.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#647 minor cleanup
  README.md
  site/content/docs/contributing/getting-started.md
  site/content/docs/contributing/project-structure.md
  site/content/docs/design/principles.md
  site/content/docs/user/known-issues.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#649 Fix creating bindir
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#650 Fix kindnetd ipv6
  cmd/kindnetd/cni.go
  cmd/kindnetd/main.go
  cmd/kindnetd/util.go
  images/kindnetd/VERSION
  pkg/build/node/cni.go
Labels: approved, cncf-cla: yes, size/M

#653 Remove leftover on CoreDNS IPv6 config
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#652 docs: Adding WSL2 setup steps
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#654 validate ports, cleanup API slightly
  hack/update/generated.sh
  pkg/cluster/config/encoding/scheme.go
  pkg/cluster/config/encoding/scheme_test.go
  pkg/cluster/config/encoding/testdata/invalid-kind.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-full-ha.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-minimal.yaml
  pkg/cluster/config/encoding/testdata/v1alpha3/valid-full-ha.yaml
  pkg/cluster/config/encoding/testdata/v1alpha3/valid-minimal-two-nodes.yaml
  pkg/cluster/config/encoding/testdata/v1alpha3/valid-minimal.yaml
  pkg/cluster/config/types.go
  pkg/cluster/config/v1alpha2/conversion.go
  pkg/cluster/config/v1alpha2/default.go
  pkg/cluster/config/v1alpha2/doc.go
  pkg/cluster/config/v1alpha2/register.go
  pkg/cluster/config/v1alpha2/types.go
  pkg/cluster/config/v1alpha2/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/zz_generated.deepcopy.go
  pkg/cluster/config/v1alpha2/zz_generated.default.go
  pkg/cluster/config/v1alpha3/types.go
  pkg/cluster/config/v1alpha3/zz_generated.conversion.go
  pkg/cluster/config/v1alpha3/zz_generated.deepcopy.go
  pkg/cluster/config/validate.go
  pkg/cluster/config/zz_generated.deepcopy.go
  pkg/cluster/internal/create/nodes.go
  pkg/cluster/nodes/create.go
  pkg/container/cri/types.go
  pkg/container/docker/critoflags.go
  pkg/container/docker/run.go
  site/content/docs/contributing/project-structure.md
  site/content/docs/user/quick-start.md
  site/data/apiVersions.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#655 upgrade default image to v1.15.0
  pkg/cluster/config/defaults/image.go
Labels: approved, lgtm

#656 Release 0.4.0
  cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, size/XS

#657 update install directions for v0.4.0
  README.md
  site/content/_index.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#664 Link `/dev/kmsg` to `/dev/console`
  images/base/entrypoint
Labels: approved, cncf-cla: yes, lgtm, size/S

#665 entrypoint: logging and minor nits
  images/base/entrypoint
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#670 port improvements from kubernetes/release to shellcheck script
  hack/verify/shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
