Repository kubernetes-sigs/kind, pull requests merged in 2019-01, with the labels that each got.

#196 Updates README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#201 Add 2019 roadmap
  docs/README.md
  docs/roadmap.md
  docs/todo.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#202 Fix typo
  pkg/cluster/context.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/backlog, size/XS

#147 Multi node config
  Gopkg.lock
  Gopkg.toml
  cmd/kind/create/cluster/createcluster.go
  pkg/cluster/config/encoding/scheme.go
  pkg/cluster/config/encoding/scheme_test.go
  pkg/cluster/config/encoding/testdata/invalid-apiversion.yaml
  pkg/cluster/config/encoding/testdata/invalid-kind.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-full-ha.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-minimal-two-nodes.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-with-lifecyclehooks.yaml
  pkg/cluster/config/fuzzer/fuzzer.go
  pkg/cluster/config/helpers.go
  pkg/cluster/config/helpers_test.go
  pkg/cluster/config/register.go
  pkg/cluster/config/types.go
  pkg/cluster/config/v1alpha1/conversion.go
  pkg/cluster/config/v1alpha1/register.go
  pkg/cluster/config/v1alpha1/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/default.go
  pkg/cluster/config/v1alpha2/register.go
  pkg/cluster/config/v1alpha2/types.go
  pkg/cluster/config/v1alpha2/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/zz_generated.deepcopy.go
  pkg/cluster/config/v1alpha2/zz_generated.default.go
  pkg/cluster/config/validate.go
  pkg/cluster/config/validate_test.go
  pkg/cluster/config/zz_generated.deepcopy.go
  pkg/cluster/context.go
  vendor/k8s.io/utils/LICENSE
  vendor/k8s.io/utils/pointer/pointer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#204 Revert "Multi node config"
  Gopkg.lock
  Gopkg.toml
  cmd/kind/create/cluster/createcluster.go
  pkg/cluster/config/encoding/scheme.go
  pkg/cluster/config/encoding/scheme_test.go
  pkg/cluster/config/encoding/testdata/invalid-apiversion.yaml
  pkg/cluster/config/encoding/testdata/invalid-kind.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-full-ha.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-minimal-two-nodes.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-with-lifecyclehooks.yaml
  pkg/cluster/config/fuzzer/fuzzer.go
  pkg/cluster/config/helpers.go
  pkg/cluster/config/helpers_test.go
  pkg/cluster/config/register.go
  pkg/cluster/config/types.go
  pkg/cluster/config/v1alpha1/conversion.go
  pkg/cluster/config/v1alpha1/register.go
  pkg/cluster/config/v1alpha1/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/default.go
  pkg/cluster/config/v1alpha2/register.go
  pkg/cluster/config/v1alpha2/types.go
  pkg/cluster/config/v1alpha2/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/zz_generated.deepcopy.go
  pkg/cluster/config/v1alpha2/zz_generated.default.go
  pkg/cluster/config/validate.go
  pkg/cluster/config/validate_test.go
  pkg/cluster/config/zz_generated.deepcopy.go
  pkg/cluster/context.go
  vendor/k8s.io/utils/LICENSE
  vendor/k8s.io/utils/pointer/pointer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#206 Restore multinode config
  Gopkg.lock
  cmd/kind/create/cluster/createcluster.go
  hack/update-generated.sh
  pkg/cluster/actions.go
  pkg/cluster/actions_test.go
  pkg/cluster/config/encoding/scheme.go
  pkg/cluster/config/encoding/scheme_test.go
  pkg/cluster/config/encoding/testdata/invalid-apiversion.yaml
  pkg/cluster/config/encoding/testdata/invalid-kind.yaml
  pkg/cluster/config/encoding/testdata/invalid-no-apiversion.yaml
  pkg/cluster/config/encoding/testdata/invalid-no-kind.yaml
  pkg/cluster/config/encoding/testdata/v1alpha1/invalid-minimal-two-nodes.yaml
  pkg/cluster/config/encoding/testdata/v1alpha1/valid-with-lifecyclehooks.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/invalid-minimal-duplicated-names.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-full-ha.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-minimal-two-nodes.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-minimal.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-with-lifecyclehooks.yaml
  pkg/cluster/config/fuzzer/fuzzer.go
  pkg/cluster/config/helpers.go
  pkg/cluster/config/helpers_test.go
  pkg/cluster/config/register.go
  pkg/cluster/config/types.go
  pkg/cluster/config/v1alpha1/conversion.go
  pkg/cluster/config/v1alpha1/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/default.go
  pkg/cluster/config/v1alpha2/register.go
  pkg/cluster/config/v1alpha2/types.go
  pkg/cluster/config/v1alpha2/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/zz_generated.deepcopy.go
  pkg/cluster/config/v1alpha2/zz_generated.default.go
  pkg/cluster/config/validate.go
  pkg/cluster/config/validate_test.go
  pkg/cluster/config/zz_generated.deepcopy.go
  pkg/cluster/context.go
  pkg/cluster/kubeadm-config.go
  pkg/cluster/kubeadm-init.go
  pkg/cluster/kubeadm-join.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#207 eliminate lifecycle hooks
  docs/user/kind-example-config.yaml
  pkg/cluster/config/encoding/testdata/v1alpha2/valid-with-lifecyclehooks.yaml
  pkg/cluster/config/types.go
  pkg/cluster/config/v1alpha1/conversion.go
  pkg/cluster/config/v1alpha1/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/types.go
  pkg/cluster/config/v1alpha2/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/zz_generated.deepcopy.go
  pkg/cluster/config/validate.go
  pkg/cluster/config/validate_test.go
  pkg/cluster/config/zz_generated.deepcopy.go
  pkg/cluster/context.go
  pkg/cluster/kubeadm-init.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#209 make derived configd data and actions private, computed at cluster cr…
  cmd/kind/create/cluster/createcluster.go
  pkg/cluster/actions.go
  pkg/cluster/actions_test.go
  pkg/cluster/config/encoding/scheme.go
  pkg/cluster/config/encoding/scheme_test.go
  pkg/cluster/config/helpers.go
  pkg/cluster/config/types.go
  pkg/cluster/config/v1alpha1/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/zz_generated.conversion.go
  pkg/cluster/config/validate.go
  pkg/cluster/config/validate_test.go
  pkg/cluster/config/zz_generated.deepcopy.go
  pkg/cluster/context.go
  pkg/cluster/derived.go
  pkg/cluster/derived_test.go
  pkg/cluster/kubeadm-config.go
  pkg/cluster/kubeadm-init.go
  pkg/cluster/kubeadm-join.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#198 New argument for 'build node-image' for passing the kuberoot
  cmd/kind/build/nodeimage/nodeimage.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, priority/backlog, size/M

#213 minor docs improvements
  README.md
  docs/roadmap.md
  docs/todo.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#210 don't warn on removing non-existent file
  pkg/cluster/context.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#215 correctly check KUBECONFIG when deleting clusters
  pkg/cluster/context.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#212 refactor
  Gopkg.lock
  pkg/cluster/config/types.go
  pkg/cluster/config/v1alpha1/types.go
  pkg/cluster/config/v1alpha2/types.go
  pkg/cluster/constants/constants.go
  pkg/cluster/context.go
  pkg/cluster/internal/create/actions.go
  pkg/cluster/internal/create/actions_test.go
  pkg/cluster/internal/create/const.go
  pkg/cluster/internal/create/createcontext.go
  pkg/cluster/internal/create/derivedconfig.go
  pkg/cluster/internal/create/derivedconfig_test.go
  pkg/cluster/internal/create/kubeadm-config.go
  pkg/cluster/internal/create/kubeadm-init.go
  pkg/cluster/internal/create/kubeadm-join.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/cluster/internal/kubeadm/const.go
  pkg/cluster/internal/kubeadm/doc.go
  pkg/cluster/internal/meta/meta.go
  pkg/cluster/nodes/create.go
  pkg/cluster/nodes/nodes.go
  vendor/k8s.io/client-go/util/homedir/homedir.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#221 Updated user docs with images
  docs/user/README.md
  docs/user/images/docker-pref-1.png
  docs/user/images/docker-pref-2.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#223 adding "why kind?" and alternatives list
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#225 cross build for windows as well
  hack/build/cross.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#226 tag 0.1.0 release
  cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#227 create cluster with --wait was in the wrong part of readme
  docs/user/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#230 remove outdated todo
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#232 document multi-node cluster config
  docs/user/README.md
  docs/user/kind-example-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#218 Fix typo in controlPlane JSON tag
  pkg/cluster/config/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#231 Change ownership of tarballs
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#241 fix documentation config example
  docs/user/kind-example-config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#242 Remove dependency constraints on master branches
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#238 cleanup: use `pkg/errors` instead of `fmt.Errorf()` in `/pkg/build` and `/pkg/docker`
  pkg/build/kube/aptbits.go
  pkg/build/kube/bits.go
  pkg/build/kube/source.go
  pkg/build/kube/version.go
  pkg/build/node/node.go
  pkg/docker/archive.go
  pkg/docker/run.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#239 cleanup: use `pkg/errors` instead of `fmt.Errorf()` in `/pkg/cluster`
  pkg/cluster/config/v1alpha1/conversion.go
  pkg/cluster/config/validate.go
  pkg/cluster/context.go
  pkg/cluster/internal/create/actions.go
  pkg/cluster/internal/create/createcontext.go
  pkg/cluster/internal/create/derivedconfig.go
  pkg/cluster/internal/create/kubeadm-config.go
  pkg/cluster/internal/create/kubeadm-init.go
  pkg/cluster/internal/create/kubeadm-join.go
  pkg/cluster/nodes/node.go
  pkg/cluster/nodes/nodes.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#248 Make cluster topology discoverable (after create)
  pkg/cluster/nodes/create.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, priority/important-longterm, size/S

#250 run e2e with multiple nodes
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/M

#251 fix broken link
  images/base/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS
