Repository kubernetes-sigs/kind, pull requests merged in 2019-02, with the labels that each got.

#279 Adding one more related project
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#283 Add link to documentation to README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#285 site: fix scrollbars for pre
  site/assets/css/inline.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#287 Add known issues
  site/assets/css/inline.css
  site/config.toml
  site/content/_index.md
  site/content/docs/user/known-issues.md
  site/content/docs/user/quick-start.md
  site/layouts/partials/navbar.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#272 Updated link to docs in OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#286 docker: Remove unneeded quotes from the inspect format string
  pkg/cluster/nodes/node.go
  pkg/docker/inspect.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#288 More docs enhancements
  site/assets/css/inline.css
  site/content/docs/roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#289 site: handle resize
  site/assets/js/inline.js
Labels: approved, cncf-cla: yes, size/S

#275 Pass PROXY environment variables to nodes
  pkg/cluster/nodes/create.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, priority/important-longterm, size/S

#290 improve docs, add design principles
  README.md
  site/assets/css/inline.css
  site/assets/js/inline.js
  site/config.toml
  site/content/_index.md
  site/content/docs/_index.md
  site/content/docs/design/base-image.md
  site/content/docs/design/initial.md
  site/content/docs/design/node-image.md
  site/content/docs/design/principles.md
  site/content/docs/devel/getting-started.md
  site/content/docs/devel/project-structure.md
  site/content/docs/roadmap.md
  site/content/docs/user/images/docker-pref-build.png
  site/content/docs/user/known-issues.md
  site/content/docs/user/quick-start.md
  site/layouts/partials/footer.html
  site/layouts/partials/navbar.html
  site/static/third_party/GitHub-Mark-120px-plus.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#291 add CC-BY-4.0 LICENSE to site
  site/LICENSE
Labels: approved, cncf-cla: yes, lgtm, size/L

#292 Upgrade images
  pkg/build/node/node.go
  pkg/cluster/config/defaults/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#293 disable disk eviction by default
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#294 correct baseURL, set favicon
  README.md
  netlify.toml
  site/Makefile
  site/README.md
  site/config.toml
  site/layouts/partials/header.html
  site/layouts/partials/navbar.html
  site/layouts/partials/sidebar.html
  site/static/android-chrome-192x192.png
  site/static/android-chrome-512x512.png
  site/static/apple-touch-icon.png
  site/static/browserconfig.xml
  site/static/favicon-16x16.png
  site/static/favicon-32x32.png
  site/static/favicon.ico
  site/static/mstile-150x150.png
  site/static/safari-pinned-tab.svg
  site/static/site.webmanifest
Labels: approved, cncf-cla: yes, lgtm, size/L

#295 docs improvements
  site/assets/css/inline.css
  site/config.toml
  site/content/docs/design/base-image.md
  site/content/docs/design/initial.md
  site/content/docs/design/node-image.md
  site/content/docs/design/principles.md
  site/content/docs/devel/getting-started.md
  site/content/docs/devel/project-structure.md
  site/content/docs/roadmap.md
  site/content/docs/user/known-issues.md
  site/content/docs/user/quick-start.md
  site/layouts/partials/sidebar.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#296 doc: fix urls
  images/base/Dockerfile
  pkg/build/base/sources/images_sources.go
  site/content/docs/design/base-image.md
  site/content/docs/design/node-image.md
  site/content/docs/devel/project-structure.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#298 doc: fix paths.
  README.md
  images/base/README.md
  images/node/README.md
  site/content/_index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#301 expand contributing docs
  README.md
  site/assets/css/inline.css
  site/config.toml
  site/content/_index.md
  site/content/docs/contributing/1.0-roadmap.md
  site/content/docs/contributing/getting-started.md
  site/content/docs/contributing/project-scope.md
  site/content/docs/contributing/project-structure.md
  site/content/docs/design/principles.md
  site/content/docs/devel/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#304 fix logging in e2e.sh
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#307 Pass NO_PROXY environment variable to nodes
  pkg/cluster/nodes/create.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#309 ensure all go get references have update flag
  README.md
  hack/ci/e2e.sh
  site/content/_index.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#308 Implements a new command "load" which allows images to be loaded
  cmd/kind/kind.go
  cmd/kind/load/docker-image/docker-image.go
  cmd/kind/load/image-archive/image-archive.go
  cmd/kind/load/load.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#310 Improve load subcommand
  cmd/kind/load/docker-image/docker-image.go
  cmd/kind/load/image-archive/image-archive.go
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#311 fix kind export logs
  cmd/kind/export/logs/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#312 Fix typos in comment and fix site link
  pkg/cluster/config/types.go
  pkg/cluster/config/v1alpha2/types.go
  site/content/docs/contributing/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#314 improve contributor docs
  site/content/docs/contributing/getting-started.md
  site/content/docs/contributing/project-scope.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#315 library - fix config validation
  pkg/cluster/config/validate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#316 library - get role
  pkg/cluster/nodes/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#313 refactor container packages and support mounts
  cmd/kind/load/docker-image/docker-image.go
  pkg/build/node/node.go
  pkg/cluster/config/types.go
  pkg/cluster/config/v1alpha2/types.go
  pkg/cluster/config/v1alpha2/zz_generated.conversion.go
  pkg/cluster/config/v1alpha2/zz_generated.deepcopy.go
  pkg/cluster/config/zz_generated.deepcopy.go
  pkg/cluster/internal/create/createcontext.go
  pkg/cluster/nodes/create.go
  pkg/cluster/nodes/node.go
  pkg/container/cri/doc.go
  pkg/container/cri/json.go
  pkg/container/cri/types.go
  pkg/container/docker/archive.go
  pkg/container/docker/cp.go
  pkg/container/docker/critoflags.go
  pkg/container/docker/doc.go
  pkg/container/docker/exec.go
  pkg/container/docker/inspect.go
  pkg/container/docker/kill.go
  pkg/container/docker/pull.go
  pkg/container/docker/run.go
  pkg/container/docker/save.go
  pkg/container/docker/userns_remap.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#319 print kubeadm init and join combined output for loglevel 'debug'
  pkg/cluster/internal/create/const.go
  pkg/cluster/internal/create/kubeadm-init.go
  pkg/cluster/internal/create/kubeadm-join.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#318 library - Refactor create options
  cmd/kind/create/cluster/createcluster.go
  pkg/cluster/context.go
  pkg/cluster/internal/create/createcontext.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#326 Windows: print message how to use with PowerShell, bash, cmd
  pkg/cluster/context.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-longterm, size/M

#327 spelling: add a new hack/verify-spelling script
  cmd/kind/load/docker-image/docker-image.go
  cmd/kind/load/image-archive/image-archive.go
  hack/verify-all.sh
  hack/verify-spelling.sh
  pkg/cluster/config/v1alpha1/conversion.go
  pkg/cluster/context.go
  pkg/cluster/internal/create/kubeadm-join.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/cluster/nodes/node.go
  pkg/container/cri/json.go
  pkg/container/cri/types.go
  pkg/container/docker/exec.go
  pkg/kustomize/kustomize.go
  site/content/docs/_index.md
  site/content/docs/contributing/1.0-roadmap.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-longterm, size/L

#331 pre-load CNI
  pkg/build/node/const.go
  pkg/build/node/node.go
  pkg/cluster/internal/create/kubeadm-init.go
  pkg/container/docker/exec.go
  pkg/exec/exec.go
  pkg/exec/local.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#322 configure Docker daemon to use proxy
  pkg/cluster/internal/create/createcontext.go
  pkg/cluster/nodes/node.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-longterm, size/M

#333 cluster/context: fix indentation for example commands
  pkg/cluster/context.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#334 upgrade default node image
  pkg/cluster/config/defaults/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#335 switch off of the bazel debs
  pkg/build/kube/bazelbuildbits.go
  pkg/build/kube/bits.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/L

#343 fix panic on create/config validation
  cmd/kind/create/cluster/createcluster.go
  pkg/cluster/config/validate.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, size/XS

#338 Refactoring: use WriteFile API to copy haproxy and kubeadm configs
  pkg/cluster/internal/create/haproxy.go
  pkg/cluster/internal/create/kubeadm-config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#346 base-image: inherit the host environment when building
  pkg/build/base/base.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-longterm, size/XS

#355 fix broken link
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#337 Added kind build node --type limitations
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#356 kubernetes behavior with image side loading and :latest tag
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S
