Repository kubernetes-sigs/kind, pull requests merged in 2019-11, with the labels that each got.

#1038 doc: Fix minor issue with kernel output path
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1039 add more test coverage
  cmd/kind/version/version_test.go
  pkg/build/node/internal/container/docker/image_test.go
  pkg/build/node/node.go
  pkg/errors/aggregate_test.go
  pkg/errors/concurrent.go
  pkg/errors/concurrent_test.go
  pkg/errors/errors_test.go
  pkg/internal/apis/config/encoding/load_test.go
  pkg/internal/apis/config/validate_test.go
  pkg/internal/build/kube/bazelbuildbits.go
  pkg/internal/build/kube/bits.go
  pkg/internal/build/kube/dockerbuildbits.go
  pkg/internal/cluster/logs/logs.go
  pkg/internal/cluster/providers/provider/common/getport_test.go
  pkg/internal/cluster/providers/provider/common/images_test.go
  pkg/internal/cluster/providers/provider/common/namer_test.go
  pkg/internal/cluster/providers/provider/common/proxy_test.go
  pkg/internal/util/assert/assert_test.go
  pkg/internal/util/env/osarch.go
  pkg/internal/util/env/term_test.go
  pkg/internal/util/kubeconfig/encode_test.go
  pkg/internal/util/kubeconfig/helpers_test.go
  pkg/internal/util/kubeconfig/homedir.go
  pkg/internal/util/kubeconfig/merge_test.go
  pkg/internal/util/kubeconfig/paths.go
  pkg/internal/util/kubeconfig/paths_test.go
  pkg/internal/util/kubeconfig/read_test.go
  pkg/internal/util/kubeconfig/remove_test.go
  pkg/internal/util/kubeconfig/write_test.go
  pkg/internal/util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1041 Cleanup old / unused code
  pkg/apis/config/v1alpha3/json.go
  pkg/apis/config/v1alpha3/types.go
  pkg/build/node/internal/container/cri/doc.go
  pkg/build/node/internal/container/cri/json.go
  pkg/build/node/internal/container/cri/types.go
  pkg/build/node/internal/container/cri/yaml.go
  pkg/build/node/internal/container/docker/cp.go
  pkg/build/node/internal/container/docker/critoflags.go
  pkg/build/node/internal/container/docker/run.go
  pkg/build/node/node.go
  pkg/cluster/doc.go
  pkg/cluster/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1043 minor update to base image docs
  site/content/docs/design/base-image.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1044 carry PR 807
  README.md
  site/content/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1049 doc:Fix public Windows insider preview build number
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1040 update to go 1.13.4
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1052 Get expects an 'external' bool but we give it and 'internal'
  pkg/cluster/provider.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1054 avoid tempfiles cleanup collision
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/node/node.go
  pkg/internal/cluster/logs/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1056 Fix race in TestAggregateConcurrent.
  pkg/errors/concurrent_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1058 test cleanup: dedupe reflect.DeepEqual boilerplate
  pkg/errors/aggregate_test.go
  pkg/errors/concurrent_test.go
  pkg/errors/errors_test.go
  pkg/internal/cluster/kubeconfig/internal/kubeconfig/paths_test.go
  pkg/internal/cluster/kubeconfig/internal/kubeconfig/remove_test.go
  pkg/internal/cluster/providers/provider/common/namer_test.go
  pkg/internal/cluster/providers/provider/common/proxy_test.go
  pkg/internal/util/assert/assert.go
  pkg/internal/util/assert/assert_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1059 fix cli.Logger.writeBuffer
  pkg/internal/util/cli/logger.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1057 bikeshed quiet handling and add tests
  cmd/kind/app/main.go
  cmd/kind/app/main_test.go
  pkg/cmd/kind/root.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1065 Use stdin from streams in create cluster
  pkg/cluster/createoption.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/internal/apis/config/encoding/load.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1066 Fix pipe closing race in kind export logs
  pkg/exec/helpers.go
  pkg/internal/cluster/logs/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1067 Update dependencies
  go.mod
  go.sum
  pkg/build/node/node.go
  pkg/internal/util/env/term.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1071 remove unnecessary .dockerignore
  .dockerignore
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#1069 minor cli fixes
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/cmd/kind/get/kubeconfig/kubeconfig.go
  pkg/cmd/kind/root.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#1068 add `kind export kubeconfig`
  pkg/cluster/provider.go
  pkg/cmd/kind/export/export.go
  pkg/cmd/kind/export/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#1072 Update tools
  Makefile
  hack/go_container.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/build/node/internal/kube/bazelbuildbits.go
  pkg/build/node/internal/kube/dockerbuildbits.go
  pkg/build/node/internal/kube/version.go
  pkg/internal/cluster/kubeconfig/internal/kubeconfig/paths_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#1075 eliminate klog indirect dependency
  pkg/internal/util/patch/patch_test.go
  pkg/internal/util/patch/resource.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1076 re-arrange error message english
  pkg/cmd/kind/create/cluster/createcluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1078 update link to strategic merge docs
  pkg/apis/config/v1alpha3/types.go
  pkg/apis/config/v1alpha4/types.go
  pkg/internal/apis/config/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1079 Update patch docs.
  pkg/apis/config/v1alpha3/types.go
  pkg/apis/config/v1alpha4/types.go
  pkg/internal/apis/config/convert_v1alpha3.go
  pkg/internal/apis/config/convert_v1alpha4.go
  pkg/internal/apis/config/types.go
  pkg/internal/cluster/create/actions/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1082 make kind export logs stdout useful
  pkg/cmd/kind/export/logs/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1080 Add comments for exported function or method
  pkg/cluster/nodeutils/roles.go
  pkg/cluster/nodeutils/util.go
  pkg/internal/apis/config/convert_v1alpha3.go
  pkg/internal/apis/config/convert_v1alpha4.go
  pkg/internal/cluster/context/context.go
  pkg/internal/cluster/providers/docker/provider.go
  pkg/internal/util/cli/logger.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1087 containerd 1.3 latest backports
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1088 CLI fun
  README.md
  go.mod
  go.sum
  pkg/cluster/createoption.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/internal/cluster/create/create.go
  pkg/internal/util/cli/spinner.go
  pkg/internal/util/cli/status.go
  site/content/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1089 handle windows terminals better
  go.mod
  go.sum
  pkg/cmd/logger.go
  pkg/internal/util/cli/spinner.go
  pkg/internal/util/env/term.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1085 deepcopygen for v1alpha4
  hack/update/generated.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1090 Bump cni plugins to v0.8.3
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1092 Fix line wrapping in terminals.
  pkg/internal/util/cli/spinner.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1083 Provide ability for Worker Kubeadm Config Patches
  pkg/apis/config/v1alpha4/types.go
  pkg/apis/config/v1alpha4/zz_generated.deepcopy.go
  pkg/internal/apis/config/convert_v1alpha4.go
  pkg/internal/apis/config/encoding/load_test.go
  pkg/internal/apis/config/encoding/testdata/v1alpha4/valid-kind-workers-patches.yaml
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/zz_generated.deepcopy.go
  pkg/internal/cluster/create/actions/config/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1097 add colors to error and warning
  cmd/kind/app/main.go
  pkg/cmd/kind/root.go
  pkg/cmd/logger.go
  pkg/internal/util/cli/logger.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1104 fix 404 link
  site/content/docs/design/initial.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1105 Correct link error:404
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1106 Release v0.6.0
  hack/release/create.sh
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, size/XS

#1032 Update kubeconfig documentation
  site/content/docs/user/quick-start.md
Labels: cncf-cla: yes, do-not-merge/hold, size/M

#1107 add local registry tutorial
  site/content/docs/user/local-registry.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1108 set language on code snippet
  site/content/docs/user/local-registry.md
Labels: approved, cncf-cla: yes, size/XS

#1102 doc: Clarify Docker Desktop settings and add a hyperlinkable heading
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1110 Update kind version in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1113 update to 0.6.0 in all install references
  README.md
  site/content/_index.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, size/S

#1109 Add installation instructions for Homebrew
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1114 add homebrew to quick-start
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes

#1120 Update RBAC to v1, drop PSP
  pkg/build/node/cni.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1119 fix the script and enhance the doc
  site/content/docs/user/local-registry.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#965 Update README.md
  README.md
  site/content/docs/user/quick-start.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#1115 Added notes on loading images to named clusters
  site/content/docs/user/known-issues.md
  site/content/docs/user/quick-start.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#1129 only patch kubernetes nodes
  pkg/internal/cluster/create/actions/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1127 fix v1alpha4 parsing
  pkg/apis/config/v1alpha4/yaml.go
  pkg/internal/apis/config/encoding/load_test.go
  pkg/internal/apis/config/encoding/testdata/v1alpha4/valid-port-and-mount.yaml
  site/content/docs/user/kind-example-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
