Repository kubernetes-sigs/kind, pull requests merged in 2019-09, with the labels that each got.

#806 Remove CoreDNS hack because of k/kubeadm#1745
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#833 upgrade to go 1.13
  README.md
  cmd/kindnetd/go.mod
  hack/go_container.sh
  hack/tools/go.mod
  site/content/docs/contributing/getting-started.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#834 move status out of log package
  cmd/kind/kind.go
  pkg/internal/cluster/create/actions/action.go
  pkg/internal/cluster/create/create.go
  pkg/internal/cluster/create/images.go
  pkg/internal/cluster/create/nodes.go
  pkg/internal/util/cli/spinner.go
  pkg/internal/util/cli/status.go
  pkg/internal/util/env/term.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#836 to to -> to
  cmd/kind/export/logs/logs.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#841 create and switch to log shim and minimal logger
  cmd/kind/create/cluster/createcluster.go
  cmd/kind/kind.go
  cmd/kind/load/docker-image/docker-image.go
  go.mod
  go.sum
  pkg/build/base/base.go
  pkg/build/node/node.go
  pkg/container/docker/critoflags.go
  pkg/container/docker/pull.go
  pkg/container/docker/run.go
  pkg/exec/exec.go
  pkg/exec/local.go
  pkg/globals/logger.go
  pkg/internal/build/kube/version.go
  pkg/internal/cluster/create/actions/config/config.go
  pkg/internal/cluster/create/actions/kubeadminit/init.go
  pkg/internal/cluster/create/actions/kubeadmjoin/join.go
  pkg/internal/cluster/create/create.go
  pkg/internal/cluster/delete/delete.go
  pkg/internal/cluster/kubeadm/config.go
  pkg/internal/cluster/logs/logs.go
  pkg/internal/util/cli/status.go
  pkg/internal/util/logger/default.go
  pkg/log/doc.go
  pkg/log/noop.go
  pkg/log/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#843 log and error reporting improvements
  cmd/kind/create/cluster/createcluster.go
  cmd/kind/delete/cluster/deletecluster.go
  cmd/kind/export/logs/logs.go
  cmd/kind/get/kubeconfig/kubeconfig.go
  cmd/kind/get/nodes/nodes.go
  cmd/kind/kind.go
  cmd/kind/load/docker-image/docker-image.go
  cmd/kind/load/image-archive/image-archive.go
  pkg/build/node/node.go
  pkg/container/docker/pull.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#844 more logging / error cleanup
  cmd/kind/kind.go
  pkg/globals/logger.go
  pkg/internal/util/cli/logger.go
  pkg/internal/util/cli/spinner.go
  pkg/internal/util/cli/status.go
  pkg/internal/util/env/term.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#729 Give yet another zsh completion help/example
  cmd/kind/completion/completion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#848 migrate e2e.sh to new flags
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#847 more work on logs & errors
  cmd/kind/errors.go
  cmd/kind/kind.go
  go.mod
  go.sum
  pkg/cluster/nodes/node.go
  pkg/exec/default.go
  pkg/exec/doc.go
  pkg/exec/helpers.go
  pkg/exec/local.go
  pkg/exec/types.go
  pkg/internal/util/cli/logger.go
  pkg/internal/util/cli/spinner.go
  pkg/internal/util/cli/status.go
  pkg/log/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#855 cleanup error packages
  cmd/kind/build/baseimage/baseimage.go
  cmd/kind/build/nodeimage/nodeimage.go
  cmd/kind/create/cluster/createcluster.go
  cmd/kind/delete/cluster/deletecluster.go
  cmd/kind/errors.go
  cmd/kind/get/kubeconfig/kubeconfig.go
  cmd/kind/kind.go
  cmd/kind/load/docker-image/docker-image.go
  cmd/kind/load/image-archive/image-archive.go
  pkg/build/base/base.go
  pkg/build/node/node.go
  pkg/cluster/clusters.go
  pkg/cluster/nodes/create.go
  pkg/cluster/nodes/node.go
  pkg/cluster/nodes/nodes.go
  pkg/cluster/nodes/roles.go
  pkg/cluster/nodes/util.go
  pkg/container/docker/archive.go
  pkg/container/docker/image.go
  pkg/errors/aggregate.go
  pkg/errors/doc.go
  pkg/errors/errors.go
  pkg/exec/helpers.go
  pkg/exec/local.go
  pkg/fs/fs.go
  pkg/internal/apis/config/encoding/scheme.go
  pkg/internal/apis/config/validate.go
  pkg/internal/apis/config/validate_test.go
  pkg/internal/build/kube/bazelbuildbits.go
  pkg/internal/build/kube/bits.go
  pkg/internal/build/kube/dockerbuildbits.go
  pkg/internal/build/kube/source.go
  pkg/internal/build/kube/version.go
  pkg/internal/cluster/context/context.go
  pkg/internal/cluster/create/actions/config/config.go
  pkg/internal/cluster/create/actions/installcni/cni.go
  pkg/internal/cluster/create/actions/installstorage/storage.go
  pkg/internal/cluster/create/actions/kubeadminit/init.go
  pkg/internal/cluster/create/actions/kubeadmjoin/join.go
  pkg/internal/cluster/create/actions/loadbalancer/loadbalancer.go
  pkg/internal/cluster/create/nodes.go
  pkg/internal/cluster/delete/delete.go
  pkg/internal/cluster/kubeadm/config.go
  pkg/internal/cluster/loadbalancer/config.go
  pkg/internal/cluster/logs/logs.go
  pkg/util/concurrent/concurrent.go
  pkg/util/errors.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#853 Fix quickstart releases link
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#840 doc: Add Docker on Windows to known issues.
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#876 upgrade to go 1.13.1
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#875 Upgrade base image
  images/base/Dockerfile
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#880 Enable IPv6 on nodes
  pkg/cluster/nodeutils/util.go
  pkg/internal/cluster/providers/docker/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#882 add cluster subnets to NO_PROXY, simplify loadbalancer arguments, str…
  pkg/internal/cluster/providers/docker/provider.go
  pkg/internal/cluster/providers/docker/provision.go
  pkg/internal/cluster/providers/provider/common/getport.go
  pkg/internal/cluster/providers/provider/common/proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#883 Perfect documentations again
  images/kindnetd/cmd/kindnetd/main.go
  pkg/container/docker/critoflags.go
  pkg/exec/default.go
  pkg/internal/build/kube/dockerbuildbits.go
  pkg/internal/cluster/create/actions/waitforready/waitforready.go
  pkg/internal/util/cli/logger.go
  site/content/docs/design/principles.md
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#886 Update quick-start.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#885 Update to Kustomize 3.2.0
  go.mod
  go.sum
  pkg/internal/util/kustomize/kustomize.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#892 get the unit test ball rolling
  Makefile
  pkg/internal/util/assert/assert.go
  pkg/internal/util/kustomize/kustomize.go
  pkg/internal/util/kustomize/kutomize_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
