Repository kubernetes-sigs/kind, pull requests merged in 2019-10, with the labels that each got.

#893 get junit output in tests
  Makefile
  hack/ci/build-all.sh
  hack/ci/unit.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#894 add CRI "test-handler"
  images/base/Dockerfile
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#895 Fix dockerfile multiline echo
  images/base/Dockerfile
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#897 updates rp_filter to 1
  images/base/10-network-security.conf
  images/base/Dockerfile
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#898 tidy e2e scripts
  hack/ci/e2e-k8s.sh
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#899 add script to push ci builds
  hack/ci/push-latest-cli.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#900 generate coverage html
  hack/ci/unit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#901 chmod +x push-latest-cli.sh
  hack/ci/push-latest-cli.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#902 preserve permissions on upload
  hack/ci/push-latest-cli.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#905 Update example to use 0.0.0.0 instead of 127.0.0.1
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#903 Kustomize cmd build cobra command internalized in next release
  pkg/internal/util/kustomize/kustomize.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#908 set coverpkg when running unit tests
  hack/ci/unit.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#913 only export logs once we've tried to create the cluster
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#914 tidy containerd config, make runtimeclass tests work
  hack/ci/e2e-k8s.sh
  images/base/Dockerfile
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#917 Update known-issues.md
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#920 Use containerd binares from kind-ci
  hack/release/build/ctr/README.md
  hack/release/build/ctr/cloudbuild.yaml
  hack/release/build/ctr/run.sh
  images/base/10-limits.conf
  images/base/10-restart.conf
  images/base/Dockerfile
  images/base/containerd.service
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#924 only select known roles for internal nodes
  pkg/internal/cluster/context/context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#930 Upgrade containerd with runc backport
  images/base/Dockerfile
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#931 reach parity with other kubernetes e2e testing on retrying tests
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#932 use containerd V2 runtime
  images/base/Dockerfile
  images/base/containerd-config.toml
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#934 bump node image to v1.16.1
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#935 Remove virtuakube from alternatives.
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#936 also update docs
  site/content/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#938 A little mistake:staticcheck and fix-up typo
  cmd/kind/load/docker-image/docker-image.go
  pkg/internal/apis/config/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#940 use normal containerd version strings, update containerd with latest patches
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#946 aggregate log export errors, ignore changed files
  pkg/errors/aggregate.go
  pkg/internal/apis/config/validate_test.go
  pkg/internal/cluster/logs/logs.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/M

#947 Fix Kindnet ip-masq-agent panics
  images/kindnetd/VERSION
  images/kindnetd/cmd/kindnetd/main.go
  images/kindnetd/cmd/kindnetd/masq.go
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/apis/config/defaults/image.go
  pkg/build/node/cni.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/L

#951 temporarily bypass docker hub in kubernetes CI
  hack/ci/e2e-k8s.sh
  hack/go_container.sh
Labels: approved, cncf-cla: yes, priority/critical-urgent, size/XS

#912 roll our own strict config loading
  go.mod
  go.sum
  hack/update/generated.sh
  pkg/apis/config/v1alpha3/default.go
  pkg/apis/config/v1alpha3/register.go
  pkg/apis/config/v1alpha3/types.go
  pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha3/zz_generated.default.go
  pkg/cluster/create/cluster.go
  pkg/container/cri/json.go
  pkg/container/cri/yaml.go
  pkg/internal/apis/config/convert.go
  pkg/internal/apis/config/default.go
  pkg/internal/apis/config/encoding/convert.go
  pkg/internal/apis/config/encoding/load.go
  pkg/internal/apis/config/encoding/scheme.go
  pkg/internal/apis/config/fuzzer/fuzzer.go
  pkg/internal/apis/config/register.go
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/v1alpha3/doc.go
  pkg/internal/apis/config/v1alpha3/register.go
  pkg/internal/apis/config/v1alpha3/zz_generated.conversion.go
  pkg/internal/apis/config/validate_test.go
  pkg/internal/apis/config/zz_generated.deepcopy.go
  pkg/internal/apis/config/zz_generated.default.go
  pkg/internal/cluster/create/create.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#952 Revert "Merge pull request #951 from BenTheElder/docker-hub-is-down"
  hack/ci/e2e-k8s.sh
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#954 fix extraPortMappings / extraMounts and add more tests
  pkg/container/cri/yaml.go
  pkg/internal/apis/config/encoding/load_test.go
  pkg/internal/apis/config/encoding/testdata/v1alpha3/invalid-bad-indent.yaml
  pkg/internal/apis/config/encoding/testdata/v1alpha3/invalid-bogus-field.yaml
  pkg/internal/apis/config/encoding/testdata/v1alpha3/valid-many-fields.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#957 don't specify kube-root in e2e-k8s.sh
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#959 docs: few clarifications for Windows
  README.md
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#961 upgrade to go 1.13.3 (CVE-2019-17596)
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#963 remove bazel platforms flag since cross compiling doesn't work anyhow
  pkg/internal/build/kube/bazelbuildbits.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#967 fix cross.sh on macOS
  hack/release/build/cross.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#968 unit testing: cover kind only
  hack/ci/unit.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#972 synchronize exec combined output buffer when necessary
  pkg/exec/local.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/M

#969 provider/common tests
  pkg/internal/cluster/providers/provider/common/getport_test.go
  pkg/internal/cluster/providers/provider/common/images_test.go
  pkg/internal/cluster/providers/provider/common/namer_test.go
  pkg/internal/cluster/providers/provider/common/proxy.go
  pkg/internal/cluster/providers/provider/common/proxy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#964 use json-patch
  go.mod
  go.sum
  pkg/internal/cluster/create/actions/config/config.go
  pkg/internal/cluster/kubeadm/config.go
  pkg/internal/util/kustomize/kustomize.go
  pkg/internal/util/patch/json6902patch.go
  pkg/internal/util/patch/matchinfo.go
  pkg/internal/util/patch/mergepatch.go
  pkg/internal/util/patch/patch.go
  pkg/internal/util/patch/patch_test.go
  pkg/internal/util/patch/resource.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#975 deflake cross.sh
  hack/release/build/cross.sh
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#977 mount xtables lock file and lib/modules in kindnetd
  pkg/build/node/cni.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#981 fix incorrect yaml tag in PatchJSON6902
  pkg/apis/config/v1alpha3/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#985 test kind config with patches
  pkg/internal/apis/config/encoding/load_test.go
  pkg/internal/apis/config/encoding/testdata/v1alpha3/valid-kind-patches.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#987 readme cleanup
  README.md
  site/content/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#988 include commit in pre-release builds
  Makefile
  cmd/kind/kind.go
  cmd/kind/version/version.go
  hack/release/create.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#984 docs: Adding troubleshooting section for WSL2
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#989 Log version
  cmd/kind/version/version.go
  hack/ci/e2e-k8s.sh
  hack/release/create.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#998 add a note about older docker releases
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#995 truncate commit in version
  cmd/kind/version/version.go
  cmd/kind/version/version_test.go
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#1000 Use klog for kindnetd #991
  images/kindnetd/cmd/kindnetd/main.go
  images/kindnetd/cmd/kindnetd/routes.go
  images/kindnetd/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#983 update example config to clarify slightly
  site/content/docs/user/kind-example-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#994 Fix known issues document mistmatched -> mismatched
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1003 Revamped base image
  .gitignore
  images/base/Dockerfile
  images/base/files/etc/containerd/config.toml
  images/base/files/etc/crictl.yaml
  images/base/files/etc/sysctl.d/10-network-security.conf
  images/base/files/etc/systemd/system/containerd.service
  images/base/files/usr/local/bin/clean-install
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1005 add some trivial retries to kindnetd
  images/kindnetd/VERSION
  images/kindnetd/cmd/kindnetd/main.go
  pkg/apis/config/defaults/image.go
  pkg/build/node/cni.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1004 minor nit
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#1008 Upgrade containerd to v1.3.0-20-g7af311b4
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1009 Fix Readme.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1013 entrypoint: fix cgroups mounts + nits
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1014 use rsync to archive logs
  pkg/exec/helpers.go
  pkg/internal/cluster/logs/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1018 update storageclass annotation to GA
  pkg/internal/cluster/create/actions/installstorage/storage.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1023 remove docker and tempdir from bootstrapping
  pkg/internal/cluster/create/actions/kubeadminit/init.go
  pkg/internal/cluster/create/actions/kubeadmjoin/join.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1024 move mount / portmapping into config types
  pkg/apis/config/v1alpha3/json.go
  pkg/apis/config/v1alpha3/types.go
  pkg/apis/config/v1alpha3/yaml.go
  pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
  pkg/internal/apis/config/convert.go
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/zz_generated.deepcopy.go
  pkg/internal/cluster/providers/docker/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1025 Go API cleanup
  cmd/kind/create/cluster/createcluster.go
  cmd/kind/delete/cluster/deletecluster.go
  cmd/kind/export/logs/logs.go
  cmd/kind/get/clusters/clusters.go
  cmd/kind/get/kubeconfig/kubeconfig.go
  cmd/kind/get/kubeconfigpath/kubeconfigpath.go
  cmd/kind/get/nodes/nodes.go
  cmd/kind/load/docker-image/docker-image.go
  cmd/kind/load/image-archive/image-archive.go
  pkg/build/node/internal/container/cri/doc.go
  pkg/build/node/internal/container/cri/json.go
  pkg/build/node/internal/container/cri/types.go
  pkg/build/node/internal/container/cri/yaml.go
  pkg/build/node/internal/container/docker/archive.go
  pkg/build/node/internal/container/docker/cp.go
  pkg/build/node/internal/container/docker/critoflags.go
  pkg/build/node/internal/container/docker/doc.go
  pkg/build/node/internal/container/docker/exec.go
  pkg/build/node/internal/container/docker/image.go
  pkg/build/node/internal/container/docker/image_test.go
  pkg/build/node/internal/container/docker/pull.go
  pkg/build/node/internal/container/docker/run.go
  pkg/build/node/internal/container/docker/save.go
  pkg/build/node/node.go
  pkg/cluster/clusters.go
  pkg/cluster/provider.go
  pkg/errors/concurrent.go
  pkg/internal/cluster/context/context.go
  pkg/internal/cluster/create/actions/config/config.go
  pkg/internal/cluster/create/actions/kubeadmjoin/join.go
  pkg/internal/cluster/logs/logs.go
  pkg/internal/cluster/providers/docker/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1026 enable relative mounts in docker provider
  pkg/internal/cluster/providers/docker/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1028 Fix product_uuid in entrypoint
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1029 kubeconfig overhaul
  cmd/kind/create/cluster/createcluster.go
  cmd/kind/delete/cluster/deletecluster.go
  cmd/kind/get/get.go
  cmd/kind/get/kubeconfigpath/kubeconfigpath.go
  hack/ci/e2e-k8s.sh
  pkg/cluster/create/cluster.go
  pkg/cluster/provider.go
  pkg/internal/cluster/context/context.go
  pkg/internal/cluster/create/actions/kubeadminit/init.go
  pkg/internal/cluster/create/create.go
  pkg/internal/cluster/create/types/types.go
  pkg/internal/cluster/delete/delete.go
  pkg/internal/cluster/kubeconfig/kubeconfig.go
  pkg/internal/util/kubeconfig/encode.go
  pkg/internal/util/kubeconfig/encode_test.go
  pkg/internal/util/kubeconfig/helpers.go
  pkg/internal/util/kubeconfig/helpers_test.go
  pkg/internal/util/kubeconfig/homedir.go
  pkg/internal/util/kubeconfig/lock.go
  pkg/internal/util/kubeconfig/merge.go
  pkg/internal/util/kubeconfig/merge_test.go
  pkg/internal/util/kubeconfig/paths.go
  pkg/internal/util/kubeconfig/read.go
  pkg/internal/util/kubeconfig/read_test.go
  pkg/internal/util/kubeconfig/remove.go
  pkg/internal/util/kubeconfig/remove_test.go
  pkg/internal/util/kubeconfig/types.go
  pkg/internal/util/kubeconfig/write.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1031 enable logging in kindnetd 🙃
  images/kindnetd/VERSION
  images/kindnetd/cmd/kindnetd/main.go
  pkg/build/node/cni.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1037 add tests to assert package
  pkg/internal/util/assert/assert.go
  pkg/internal/util/assert/assert_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#1036 increase kubeconfig unit test coverage
  pkg/internal/util/kubeconfig/homedir.go
  pkg/internal/util/kubeconfig/merge.go
  pkg/internal/util/kubeconfig/merge_test.go
  pkg/internal/util/kubeconfig/paths.go
  pkg/internal/util/kubeconfig/paths_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1033 Fix typo of docs/design/principles
  site/content/docs/design/principles.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
