Repository kubernetes-sigs/kind, pull requests merged in 2019-08, with the labels that each got.

#753 clarify go support, call out strongly to the docs site
  README.md
  site/content/_index.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#752 docs: add resources, fix weighting
  site/content/docs/user/resources.md
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#754 tidy up youtube embeds
  site/assets/css/inline.css
  site/config.toml
  site/content/docs/user/resources.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#755 fix markdown parsing for go version
  site/content/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#757 docs: ensure the sidebar stays above embedded videos
  site/assets/css/inline.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#760 Set LimitNOFILE=1048576 in containerd unit file to match upstream containerd.
  images/base/10-limits.conf
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#764 cleanup: create.go words correction.
  pkg/cluster/nodes/create.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, priority/backlog, size/XS

#756 Updates private registry programmatic key addition docs
  site/content/docs/user/private-registries.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#767 Node image contains only one pulled image
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#768 bump go to 1.12.8
  README.md
  hack/build/go_container.sh
  site/content/docs/contributing/getting-started.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#714 Add note for docker permission
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#773 use anonymous volume for /var/lib/kubelet
  pkg/cluster/nodes/create.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#749 iterate on the roadmap
  site/content/docs/contributing/1.0-roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#772 update to go 1.12.9
  README.md
  hack/build/go_container.sh
  site/content/docs/contributing/getting-started.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#775 update docs to reflect removed apt build
  README.md
  site/content/_index.md
  site/content/docs/user/known-issues.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#776 compare host and node image ID when loading images
  cmd/kind/load/docker-image/docker-image.go
  pkg/cluster/nodes/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#779 make /var a runtime volume
  images/base/entrypoint
  pkg/build/node/node.go
  pkg/cluster/nodes/create.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#778 Improved installation snippet in readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#782 upgrade default node image to v1.15.3
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#780 update quick-start install docs following readme update
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#783 mark v0.5.0
  cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#785 correct api redirects
  site/layouts/index.redirects
Labels: approved, cncf-cla: yes, size/XS

#784 update install docs to point to latest release
  README.md
  site/content/_index.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, size/S

#786 refactor e2e.sh
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#794 fix release process
  go.mod
  go.sum
  hack/ci/build-all.sh
  hack/release/build/cross.sh
  hack/release/create.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#797 cleanup cross.sh
  hack/release/build/cross.sh
  hack/release/create.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#798 ensure we get a combined status from the cross build
  hack/release/build/cross.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#800 Cleanup: fix some typos in code comment
  pkg/fs/fs.go
  pkg/internal/build/kube/bits.go
  pkg/internal/build/kube/dockerbuildbits.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#801 Update IPv6 instructions in quickstart
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#803 patch coreDNS config instead of replacing it outright
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#796 Adds services account auth example to private registry docs
  site/content/docs/user/private-registries.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#805 improve repo tooling
  Makefile
  hack/build/go_container.sh
  hack/ci/build-all.sh
  hack/ci/e2e.sh
  hack/go_container.sh
  hack/release/build/cross.sh
  hack/release/build/ctr/run.sh
  hack/release/build/push-base.sh
  hack/release/build/push-node.sh
  hack/release/create.sh
  hack/tools/boilerplate.go.txt
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/update/all.sh
  hack/update/deps.sh
  hack/update/generated.sh
  hack/update/gofmt.sh
  hack/verify/all.sh
  hack/verify/generated.sh
  hack/verify/gofmt.sh
  hack/verify/govet.sh
  hack/verify/lint.sh
  hack/verify/shellcheck.sh
  hack/verify/spelling.sh
  hack/verify/staticcheck.sh
  images/kindnetd/build.sh
  pkg/build/node/node.go
  pkg/cluster/create/cluster.go
  pkg/cluster/nodes/node.go
  pkg/internal/apis/config/encoding/scheme.go
  pkg/internal/build/kube/bazelbuildbits.go
  pkg/internal/build/kube/dockerbuildbits.go
  pkg/internal/build/kube/version.go
  pkg/internal/cluster/create/create.go
  pkg/internal/cluster/logs/logs.go
  pkg/internal/util/kustomize/kustomize.go
  pkg/log/status.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#810 update docs to point to 0.5.1
  README.md
  site/content/_index.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, size/S

#809 use go_container.sh more consistently
  go.mod
  hack/ci/build-all.sh
  hack/release/build/push-base.sh
  hack/release/build/push-node.sh
  hack/update/all.sh
  hack/update/deps.sh
  hack/update/generated.sh
  hack/update/gofmt.sh
Labels: approved, cncf-cla: yes, size/M

#811 enable more lints
  cmd/kind/build/baseimage/baseimage.go
  cmd/kind/build/nodeimage/nodeimage.go
  cmd/kind/create/cluster/createcluster.go
  cmd/kind/delete/cluster/deletecluster.go
  cmd/kind/export/logs/logs.go
  cmd/kind/get/clusters/clusters.go
  cmd/kind/get/kubeconfig/kubeconfig.go
  cmd/kind/get/kubeconfigpath/kubeconfigpath.go
  cmd/kind/get/nodes/nodes.go
  cmd/kind/kind.go
  cmd/kind/load/docker-image/docker-image.go
  cmd/kind/load/image-archive/image-archive.go
  hack/verify/lint.sh
  pkg/apis/config/v1alpha3/register.go
  pkg/internal/apis/config/encoding/scheme.go
  pkg/internal/apis/config/encoding/scheme_test.go
  pkg/internal/apis/config/register.go
  pkg/internal/apis/config/validate_test.go
  pkg/internal/build/kube/bazelbuildbits.go
  pkg/internal/build/kube/bits.go
  pkg/internal/build/kube/dockerbuildbits.go
  pkg/internal/cluster/create/actions/kubeadmjoin/join.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#812 Lint kindnetd
  cmd/kindnetd/cni.go
  cmd/kindnetd/main.go
  cmd/kindnetd/masq.go
  hack/verify/lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#813 Add internal domain to CoreDNS for IPv6
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#823 Fixed link to code-of-conduct
  site/content/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#827 Update to go 1.13rc2
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
