Repository kubernetes-sigs/kind, pull requests merged in 2020-10, with the labels that each got.

#1881 fix issue template to match new label
  .github/ISSUE_TEMPLATE/question.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1878 Fix typos in documentation
  README.md
  hack/ci/push-latest-cli/README.md
  hack/release/build/README.md
  images/kindnetd/README.md
  site/content/docs/contributing/1.0-roadmap.md
Labels: cncf-cla: yes, ok-to-test, size/S

#1877 Add documentation how to access a service using WSL2 on Windows 10
  site/content/docs/user/using-wsl2.md
Labels: cncf-cla: yes, ok-to-test, size/S

#1883 Doc features
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1885 allow to select the kube-proxy mode in CI
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1893 bump go to 1.15.3
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1896 site: update the registry docs to use the config map
  site/static/examples/kind-with-registry.sh
Labels: cncf-cla: yes, ok-to-test, size/S

#1908 added guide on setting up a local domain for use with ingress
  site/content/docs/user/resources.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1911 fix bazel build out of k/k repo
  pkg/build/nodeimage/internal/kube/builder_bazel.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#1912 Fix a typo in error message
  pkg/cluster/internal/create/actions/config/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
