Repository kubernetes-sigs/kind, pull requests merged in 2020-04, with the labels that each got.

#1418 Adding UT for port validate
  pkg/internal/apis/config/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1464 Support BTRFS and ZFS docker storage
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/docker/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1465 fix anchor links in known issues readme
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1467 Update golang to 1.14.2
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1064 offline docs
  site/content/docs/user/working-offline.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1476 Surface ipv6 configuration error.
  pkg/cluster/internal/create/actions/config/config.go
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1477 Fixed a minor typo in site contents
  site/content/docs/user/working-offline.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1479 disable escape sequences on travis CI
  pkg/internal/assert/assert.go
  pkg/internal/env/term.go
  pkg/internal/env/term_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1483 add cloudbuild for ci-latest
  hack/ci/push-latest-cli/cloudbuild.yaml
  hack/ci/push-latest-cli/push-latest-cli.sh
Labels: approved, cncf-cla: yes, size/M

#1391 Add docs note on how to list loaded images
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1484 add a quick readme to push-latest-cli
  hack/ci/push-latest-cli/README.md
Labels: cncf-cla: yes

#1485 s/command/entrypoint
  hack/ci/push-latest-cli/cloudbuild.yaml
Labels: cncf-cla: yes

#1486 correct env and path
  hack/ci/push-latest-cli/cloudbuild.yaml
  hack/ci/push-latest-cli/push-latest-cli.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1488 drop extraneous dot from path
  hack/ci/push-latest-cli/push-latest-cli.sh
Labels: cncf-cla: yes, ¯\_(ツ)_/¯

#1489 Shiny CI builds
  hack/ci/push-latest-cli/push-latest-cli.sh
  site/layouts/index.redirects
Labels: approved, cncf-cla: yes, size/M

#1490 remove extraneous slash
  hack/ci/push-latest-cli/push-latest-cli.sh
Labels: cncf-cla: yes

#1492 create redirect for release downloads
  README.md
  site/content/docs/user/quick-start.md
  site/layouts/index.redirects
Labels: approved, cncf-cla: yes, lgtm, size/S

#1491 remove old ci push script
  hack/ci/push-latest-cli.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1493 Support KIND_CLUSTER_NAME.
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/cmd/kind/delete/cluster/deletecluster.go
  pkg/cmd/kind/export/kubeconfig/kubeconfig.go
  pkg/cmd/kind/export/logs/logs.go
  pkg/cmd/kind/get/kubeconfig/kubeconfig.go
  pkg/cmd/kind/get/nodes/nodes.go
  pkg/cmd/kind/load/docker-image/docker-image.go
  pkg/cmd/kind/load/image-archive/image-archive.go
  pkg/internal/cli/override.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#1494 fix config featuregate handling
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#1495 support NO_COLOR
  pkg/internal/env/term.go
  pkg/internal/env/term_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1499 Simplify steps to install ingress-nginx
  site/content/docs/user/ingress.md
  site/static/examples/ingress/nginx/patch.json
  site/static/examples/ingress/usage.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1500 Fix bug mounting /dev/mapper
  pkg/cluster/internal/providers/docker/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1503 Set listenAddress in example to 127.0.0.1
  site/static/examples/config-with-port-mapping.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1505 refactor node image build, fix pause image alignment
  images/base/files/etc/containerd/config.toml
  pkg/build/nodeimage/build.go
  pkg/build/nodeimage/build_impl.go
  pkg/build/nodeimage/const.go
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
  pkg/build/nodeimage/const_systemd.go
  pkg/build/nodeimage/containerd_config.go
  pkg/build/nodeimage/defaults.go
  pkg/build/nodeimage/doc.go
  pkg/build/nodeimage/helpers.go
  pkg/build/nodeimage/imageimporter.go
  pkg/build/nodeimage/installcontext.go
  pkg/build/nodeimage/internal/container/docker/archive.go
  pkg/build/nodeimage/internal/container/docker/doc.go
  pkg/build/nodeimage/internal/container/docker/exec.go
  pkg/build/nodeimage/internal/container/docker/image.go
  pkg/build/nodeimage/internal/container/docker/image_test.go
  pkg/build/nodeimage/internal/container/docker/pull.go
  pkg/build/nodeimage/internal/container/docker/run.go
  pkg/build/nodeimage/internal/container/docker/save.go
  pkg/build/nodeimage/internal/kube/bazelbuildbits.go
  pkg/build/nodeimage/internal/kube/bits.go
  pkg/build/nodeimage/internal/kube/doc.go
  pkg/build/nodeimage/internal/kube/dockerbuildbits.go
  pkg/build/nodeimage/internal/kube/source.go
  pkg/build/nodeimage/internal/kube/version.go
  pkg/build/nodeimage/options.go
  pkg/cmd/kind/build/nodeimage/nodeimage.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1508 Use the network luke
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/const_storage.go
  pkg/build/nodeimage/defaults.go
  pkg/cluster/internal/context/context.go
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/providers/docker/network.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/provider/provider.go
  pkg/cluster/nodeutils/util.go
  pkg/exec/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1510 Better default info
  cmd/kind/app/main.go
  pkg/build/nodeimage/internal/container/docker/pull.go
  pkg/cluster/internal/create/create.go
  pkg/cmd/kind/create/cluster/createcluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1354 Update roadmap doc wrt podman.
  site/content/docs/contributing/1.0-roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1515 use beta label in older kubernetes
  pkg/build/nodeimage/build_impl.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1517 Upgrade binary & devel dependencies
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1516 Add fish completion support
  go.mod
  go.sum
  pkg/cmd/kind/completion/completion.go
  pkg/cmd/kind/completion/fish/fish.go
  pkg/cmd/kind/root.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1521 Fixreboot
  images/base/Dockerfile
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1526 always create network with ipv6
  pkg/cluster/internal/providers/docker/network.go
  pkg/cluster/internal/providers/docker/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#1531 improve subnet allocation
  pkg/cluster/internal/providers/docker/network.go
  pkg/cluster/internal/providers/docker/network_test.go
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1534 Fix the problem of container restart failure
  images/base/files/usr/local/bin/entrypoint
Labels: cncf-cla: yes, ok-to-test, priority/critical-urgent, size/XS

#1537 drop stale note
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1536 bump images
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
