Repository kubernetes-sigs/kind, pull requests merged in 2020-06, with the labels that each got.

#1649 revert of 1599
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/XS

#1644 Document kubeadmconfigpatches.
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1643 bump to go 1.14.4
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1651 Tighten GA_ONLY configuration to drop CSR exception for 1.19
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1669 SCTP
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1670 add notice from kubernetes.io to site
  site/assets/css/inline.css
  site/layouts/partials/navbar.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#1661 Add in-cluster pod and services dns names to no_proxy
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provision.go
  site/static/examples/ingress/usage.yaml
Labels: cncf-cla: yes, lgtm, size/S

#1671 minor site fixup
  site/assets/css/inline.css
Labels: approved, cncf-cla: yes, size/XS

#1672 more site cleanup
  site/assets/css/inline.css
  site/content/_index.md
  site/content/docs/user/configuration.md
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, size/L

#1677 Revert "Add support for dockerless builds in kind"
  pkg/build/nodeimage/internal/kube/dockerbuildbits.go
Labels: approved, cncf-cla: yes, size/XS

#1681 update debian iptables to latest
  images/kindnetd/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1688 containerd updates
  images/base/Dockerfile
  images/base/files/etc/crictl.yaml
  pkg/build/nodeimage/containerd_config.go
  pkg/build/nodeimage/defaults.go
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1683 Improve help message
  pkg/cmd/kind/load/docker-image/docker-image.go
  pkg/cmd/kind/load/image-archive/image-archive.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1697 upgrade to go 1.15beta1
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1694 Add unit test for func BoolEqual
  pkg/internal/assert/assert_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1698 Upgrade deps
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M
