Repository kubernetes-sigs/kind, pull requests merged in 2020-11, with the labels that each got.

#1917 bump to go 1.15.4
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1923 bump go to 1.15.5
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1924 disable smart output in st
  pkg/internal/env/term.go
  pkg/internal/env/term_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1925 Fix zfs
  images/base/files/etc/containerd/config.toml
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1897 site: Add TOC to configuration page, show page title in <title>, add spacing below sidebar
  site/assets/css/inline.css
  site/content/_index.md
  site/content/docs/contributing/1.0-roadmap.md
  site/content/docs/contributing/getting-started.md
  site/content/docs/contributing/project-scope.md
  site/content/docs/contributing/project-structure.md
  site/content/docs/design/base-image.md
  site/content/docs/design/initial.md
  site/content/docs/design/node-image.md
  site/content/docs/design/principles.md
  site/content/docs/user/configuration.md
  site/content/docs/user/ingress.md
  site/content/docs/user/known-issues.md
  site/content/docs/user/local-registry.md
  site/content/docs/user/private-registries.md
  site/content/docs/user/quick-start.md
  site/content/docs/user/resources.md
  site/content/docs/user/using-wsl2.md
  site/content/docs/user/working-offline.md
  site/layouts/docs/index.html
  site/layouts/docs/section.html
  site/layouts/docs/single.html
  site/layouts/index.html
  site/layouts/partials/fancymarkdown.html
  site/layouts/partials/header.html
Labels: cncf-cla: yes, ok-to-test, size/M

#1931 split unit and integration tests in makefile
  Makefile
  hack/make-rules/test.sh
  pkg/cluster/internal/providers/docker/network_integration_test.go
  pkg/cluster/internal/providers/docker/network_test.go
Labels: approved, area/provider/docker, cncf-cla: yes, lgtm, size/L

#1932 optimistically disable dockershim
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/internal/kube/builder_docker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1937 disable CGO by default
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
