Repository kubernetes-sigs/kind, pull requests merged in 2020-12, with the labels that each got.

#1936 address some minor errors in the quick-start.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1952 fixup some styling, add dedicated descriptions, add dockershim notice
  site/assets/css/inline.css
  site/content/docs/contributing/1.0-roadmap.md
  site/content/docs/contributing/getting-started.md
  site/content/docs/contributing/project-scope.md
  site/content/docs/design/initial.md
  site/content/docs/design/principles.md
  site/content/docs/user/configuration.md
  site/content/docs/user/ingress.md
  site/content/docs/user/known-issues.md
  site/content/docs/user/local-registry.md
  site/content/docs/user/private-registries.md
  site/content/docs/user/quick-start.md
  site/content/docs/user/resources.md
  site/content/docs/user/using-wsl2.md
  site/content/docs/user/working-offline.md
  site/layouts/partials/fancymarkdown.html
  site/layouts/partials/navbar.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#1953 tiny followup to updated banner
  site/layouts/partials/navbar.html
  site/layouts/shortcodes/securitygoose.html
Labels: cncf-cla: yes

#1955 improve site, start overhauling contributor guide
  CONTRIBUTING.md
  site/assets/css/inline.css
  site/content/docs/contributing/1.0-roadmap.md
  site/content/docs/contributing/development.md
  site/content/docs/contributing/getting-started.md
  site/content/docs/contributing/project-structure.md
  site/content/docs/design/base-image.md
  site/content/docs/design/node-image.md
  site/content/docs/user/quick-start.md
  site/content/docs/user/resources.md
  site/content/docs/user/working-offline.md
  site/layouts/partials/footer.html
  site/layouts/partials/sidebar.html
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1957 continue fleshing out contributor guide
  site/content/docs/contributing/development.md
  site/content/docs/user/known-issues.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1958 Docs docs docs
  site/assets/css/inline.css
  site/content/docs/contributing/development.md
  site/content/docs/contributing/getting-started.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1790 Podman network
  .github/workflows/podman.yml
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/providers/podman/network.go
  pkg/cluster/internal/providers/podman/node.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/provision.go
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, lgtm, size/L

#1959 Fix broken links in development.md
  site/content/docs/contributing/development.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1747 Support configuring a cgroup root for kubelet
  images/base/files/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  images/base/files/usr/local/bin/entrypoint
  pkg/build/nodeimage/defaults.go
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, lgtm, size/M

#1960 clarify error getting ipv6 address on node
  pkg/cluster/internal/create/actions/config/config.go
Labels: cncf-cla: yes, size/S

#1964 bump go to 1.15.6
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1962 Adding TLS certification section on private registry
  site/content/docs/user/private-registries.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#1942 Add completion for oh-my-zsh
  pkg/cmd/kind/completion/completion.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#1994 Update documentation wsl shutdown command issue1977
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
