Repository kubernetes-sigs/kind, pull requests merged in 2020-01, with the labels that each got.

#1209 Add invisible padding to clear navbar for heading links.
  site/assets/css/inline.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1220 Update kind-with-registry.sh to work out of the box
  site/static/examples/kind-with-registry.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1221 simplify enabling feature gates
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1223 fix escape for copy-paste
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1228 Remove duplicated word 'as as' in comments
  pkg/apis/config/v1alpha3/types.go
  pkg/apis/config/v1alpha4/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1227 provider-docker: remove duplicate container labels
  pkg/cluster/internal/providers/docker/provision.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1231 fail if we can't ensure image
  pkg/cluster/internal/providers/docker/images.go
  pkg/cluster/internal/providers/docker/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1232 add apparmor to known issues
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1229 Lowercase Flag Descriptions
  pkg/cmd/kind/build/nodeimage/nodeimage.go
  pkg/cmd/kind/create/cluster/createcluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1222 Capitalize Command Descriptions
  pkg/cmd/kind/build/baseimage/baseimage.go
  pkg/cmd/kind/build/nodeimage/nodeimage.go
  pkg/cmd/kind/export/export.go
  pkg/cmd/kind/export/kubeconfig/kubeconfig.go
  pkg/cmd/kind/export/logs/logs.go
  pkg/cmd/kind/get/clusters/clusters.go
  pkg/cmd/kind/get/kubeconfig/kubeconfig.go
  pkg/cmd/kind/get/nodes/nodes.go
  pkg/cmd/kind/load/docker-image/docker-image.go
  pkg/cmd/kind/load/image-archive/image-archive.go
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1237 Securing many http links to https links
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1238 Include protocol specification in extraPortMappings example
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1239 Bump cni version with portmap fix
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1241 upgrade to go 1.13.6
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1243 use kind's other kubeconfig fields if none are set in the existing co…
  pkg/cluster/internal/kubeconfig/internal/kubeconfig/merge.go
  pkg/cluster/internal/kubeconfig/internal/kubeconfig/merge_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1249 Update deps
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1251 Add missing step for nginx guide.
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1252 release v0.7.0
  pkg/apis/config/defaults/image.go
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1253 update references to stable release
  README.md
  site/content/_index.md
  site/content/docs/user/quick-start.md
Labels: cncf-cla: yes

#1247 site: Add Contour Ingress Controller as example in /docs/user/ingress
  site/content/docs/user/ingress.md
  site/static/examples/ingress/contour/patch.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1261 Use rancher/local-path-provisioner:v0.0.12
  pkg/build/node/storage.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1262 enable dynamic PVs in Kubernetes 1.11
  pkg/build/node/node.go
  pkg/build/node/storage.go
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1258 Drop apiversion from kubeadmconfigpatch.
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#1263 add featuregates to config
  pkg/apis/config/v1alpha4/types.go
  pkg/apis/config/v1alpha4/zz_generated.deepcopy.go
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/internal/apis/config/convert_v1alpha4.go
  pkg/internal/apis/config/encoding/testdata/v1alpha4/valid-many-fields.yaml
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1265 check off some items from the roadmap
  site/content/docs/contributing/1.0-roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1267 Make the docker cli overridable during build.
  Makefile
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1268 Bump golangci-lint timeout.
  hack/verify/lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1276 Drop quiet from docker commands.
  pkg/cluster/internal/providers/docker/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1277 add a little detail to logs
  pkg/cluster/internal/create/actions/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1278 add another space to salutation to help with certain terminals
  pkg/cluster/internal/create/create.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1279 upgrade CNI plugins to v0.8.5
  images/base/Dockerfile
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1285 Bump runc
  images/base/Dockerfile
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1286 Use logger instead of printf for waitforready
  pkg/cluster/internal/create/actions/waitforready/waitforready.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1293 Create initial skeleton for podman backend
  go.sum
  pkg/cluster/internal/providers/podman/constants.go
  pkg/cluster/internal/providers/podman/images.go
  pkg/cluster/internal/providers/podman/node.go
  pkg/cluster/internal/providers/podman/podman_util.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1295 explicitly default port mapping respecting IP family
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1297 bump to go 1.13.7
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1296 add experimental provider override env
  pkg/cluster/internal/providers/podman/podman_util.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1299 Fix pipes.
  pkg/exec/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1301 Fix typo in `md` file
  site/content/docs/contributing/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
