Repository kubernetes-sigs/kind, pull requests merged in 2020-02, with the labels that each got.

#1302 Enable basic podman support.
  pkg/cluster/internal/providers/docker/util.go
  pkg/cluster/internal/providers/podman/images.go
  pkg/cluster/internal/providers/podman/node.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/internal/providers/podman/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1308 New containerd new cri
  images/base/Dockerfile
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1312 Update dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1313 simplify registry proof of concept
  site/content/docs/user/local-registry.md
  site/static/examples/kind-with-registry.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1314 Parse: apiversion and kind inverted in error output
  pkg/internal/apis/config/encoding/load.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1318 sync only on aufs
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1319 stop bazel after building
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/XS

#1282 Add setting k8s versions in config to docs
  site/content/docs/user/configuration.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1323 Improve load docker-image logging
  pkg/cmd/kind/load/docker-image/docker-image.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1310 Move log export logic to providers
  pkg/cluster/internal/context/context.go
  pkg/cluster/internal/logs/logs.go
  pkg/cluster/internal/providers/docker/node.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/podman/node.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/provider/common/logs.go
  pkg/cluster/internal/providers/provider/provider.go
  pkg/cluster/nodes/types.go
  pkg/cluster/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1334 bump to go 1.13.8
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1341 More podman fixes + provider auto detection
  pkg/cluster/internal/providers/docker/images.go
  pkg/cluster/internal/providers/podman/images.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1345 Provider runtime options
  pkg/cluster/provider.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/cmd/kind/delete/cluster/deletecluster.go
  pkg/cmd/kind/delete/clusters/deleteclusters.go
  pkg/cmd/kind/export/kubeconfig/kubeconfig.go
  pkg/cmd/kind/export/logs/logs.go
  pkg/cmd/kind/get/clusters/clusters.go
  pkg/cmd/kind/get/kubeconfig/kubeconfig.go
  pkg/cmd/kind/get/nodes/nodes.go
  pkg/cmd/kind/load/docker-image/docker-image.go
  pkg/cmd/kind/load/image-archive/image-archive.go
  pkg/internal/runtime/runtime.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1348 drain reader when untarring
  pkg/cluster/internal/logs/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1349 Use a released version as min supported for podman.
  pkg/cluster/internal/providers/podman/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1351 fix abspath resolution on windows
  pkg/cluster/internal/providers/docker/provision.go
  pkg/fs/fs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1352 upgrade containerd
  images/base/Dockerfile
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1353 pick random port on host unless asked to use backend ...
  pkg/apis/config/v1alpha3/types.go
  pkg/apis/config/v1alpha4/types.go
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/internal/providers/provider/common/getport.go
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/validate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1357 Use text/template instead of html/template
  pkg/cluster/internal/create/actions/installcni/cni.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1358 Update ingress-nginx version
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1355 Update docs to ensure that kubectl is installed
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1363 upgrade to go 1.14.0
  hack/ci/e2e-k8s.sh
  hack/go_container.sh
  pkg/build/node/internal/kube/source.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1366 Base image updates
  hack/build/init-buildx.sh
  images/base/Dockerfile
  images/base/Makefile
  images/base/build.sh
  images/base/push.sh
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1368 Adds CommandContext to the Cmder interface
  pkg/build/node/internal/container/docker/exec.go
  pkg/cluster/internal/providers/docker/node.go
  pkg/cluster/internal/providers/podman/node.go
  pkg/exec/default.go
  pkg/exec/local.go
  pkg/exec/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1370 auto detect provider in build
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1371 also auto detect in makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1372 Fix make lint
  hack/verify/lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1375 clairfy kubectl install
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1376 remove kind build base-image
  pkg/build/base/base.go
  pkg/cmd/kind/build/baseimage/baseimage.go
  pkg/cmd/kind/build/build.go
  pkg/cmd/kind/build/nodeimage/nodeimage.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1377 docs: remove kind build base-image
  images/base/README.md
  site/content/docs/design/node-image.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S
