Repository kubernetes-sigs/kind, pull requests merged in 2020-09, with the labels that each got.

#1829 Add LICENSE to site examples
  site/layouts/partials/footer.html
  site/static/examples/LICENSE
Labels: cncf-cla: yes, ok-to-test, size/L

#1832 bump go to 1.15.1
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1812 add link to fedora32 article
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1833 Update links to hack scripts
  site/content/docs/contributing/project-structure.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1841 bazel: derive exec path of go binaries from action graph
  pkg/build/nodeimage/internal/kube/builder_bazel.go
Labels: approved, cncf-cla: yes, size/L

#1838 fix small typo in comment
  hack/make-rules/verify/shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1842 upgrade go to 1.15.2
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1831 fix ambiguous networks
  pkg/cluster/internal/providers/docker/network.go
  pkg/cluster/internal/providers/docker/network_test.go
  pkg/internal/integration/integration.go
Labels: approved, area/provider/docker, cncf-cla: yes, lgtm, size/L

#1848 mark v0.9.0 release
  pkg/apis/config/defaults/image.go
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/XS

#1849 update install docs for v0.9.0
  README.md
  site/content/_index.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, size/S

#1851 remove unnecessary usage of CombinedOutputLines
  pkg/build/nodeimage/build_impl.go
  pkg/build/nodeimage/internal/container/docker/image.go
  pkg/build/nodeimage/internal/container/docker/run.go
  pkg/build/nodeimage/internal/kube/source.go
  pkg/cluster/internal/create/actions/waitforready/waitforready.go
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/docker/util.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/internal/providers/podman/util.go
  pkg/cluster/nodeutils/util.go
  pkg/cmd/kind/load/docker-image/docker-image.go
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, lgtm, size/S

#1854 export logs kind version
  pkg/cluster/internal/providers/common/logs.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/podman/provider.go
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, lgtm, size/S

#1856 Update ingress example to use networking.k8s.io
  site/static/examples/ingress/usage.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#1847 bump debian iptables base image
  images/kindnetd/Dockerfile
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1859 Lint Configuration via YAML
  hack/make-rules/verify/lint.sh
  hack/tools/.golangci.yml
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, size/M

#1868 Fix indents of page quick-start.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#1870 Fix golint warning: package comment should be of the form "Package nodeimage ..."
  pkg/build/nodeimage/doc.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#1872 upgrade all the things
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  images/base/Dockerfile
  images/kindnetd/cmd/kindnetd/main.go
  images/kindnetd/cmd/kindnetd/routes.go
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/L
