Repository kubernetes-sigs/kind, pull requests merged in 2020-05, with the labels that each got.

#1538 experimentally allow custom networks
  pkg/cluster/internal/providers/docker/network.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/docker/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1539 mark v0.8.0 release
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes

#1540 s/v0.7.0/v0.8.0 in docs
  README.md
  site/content/_index.md
  site/content/docs/user/quick-start.md
Labels: cncf-cla: yes

#1528 upgrade base image
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1542 fix kind-with-registry for v0.8
  site/static/examples/kind-with-registry.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1545 handle hosts that cannot create ipv6 networks by falling back to ipv4…
  pkg/cluster/internal/providers/docker/network.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1548 install nfs common
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/XS

#1550 Update link to systemd CONTAINER_INTERFACE reference
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1549 trivial fix to a comment
  images/base/Dockerfile
Labels: cncf-cla: yes, ok-to-test, size/XS

#1551 Fix ipv6 network overlap error
  pkg/cluster/internal/providers/docker/network.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1554 Update link to systemd CONTAINER_INTERFACE reference
  images/base/Dockerfile
  images/base/files/usr/local/bin/entrypoint
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1561 Drop unnecessary kubelet arg in ingress guide.
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1564 allow loadbalancer to restart gracefully
  pkg/cluster/internal/create/actions/loadbalancer/loadbalancer.go
  pkg/cluster/internal/loadbalancer/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1573 fix NO_PROXY
  pkg/cluster/internal/providers/docker/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1576 Add support for dockerless builds in kind
  pkg/build/nodeimage/internal/kube/dockerbuildbits.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1577 fix featureGate docs to use the new top level field in Cluster config
  site/content/docs/user/quick-start.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#1587 add kindnetd readme with history
  images/haproxy/README.md
  images/kindnetd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1586 bump cni version to 0.8.6
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1588 Add one-liner to ingress-nginx to wait until ready
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1592 masquerade docker network traffic
  pkg/cluster/internal/providers/docker/network.go
Labels: cncf-cla: yes, kind/bug, size/XS

#1525 name in config
  hack/update/generated.sh
  pkg/apis/config/v1alpha3/default.go
  pkg/apis/config/v1alpha3/doc.go
  pkg/apis/config/v1alpha3/types.go
  pkg/apis/config/v1alpha3/yaml.go
  pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha4/types.go
  pkg/cluster/createoption.go
  pkg/cluster/internal/context/context.go
  pkg/cluster/internal/create/actions/action.go
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/delete/delete.go
  pkg/cluster/internal/kubeconfig/kubeconfig.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/internal/providers/provider/provider.go
  pkg/cluster/nodeutils/roles.go
  pkg/cluster/provider.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/internal/apis/config/convert_v1alpha3.go
  pkg/internal/apis/config/convert_v1alpha4.go
  pkg/internal/apis/config/default.go
  pkg/internal/apis/config/encoding/convert.go
  pkg/internal/apis/config/encoding/load.go
  pkg/internal/apis/config/encoding/load_test.go
  pkg/internal/apis/config/encoding/testdata/v1alpha3/invalid-bad-indent.yaml
  pkg/internal/apis/config/encoding/testdata/v1alpha3/invalid-bogus-field.yaml
  pkg/internal/apis/config/encoding/testdata/v1alpha3/invalid-kind.yaml
  pkg/internal/apis/config/encoding/testdata/v1alpha3/valid-full-ha.yaml
  pkg/internal/apis/config/encoding/testdata/v1alpha3/valid-kind-patches.yaml
  pkg/internal/apis/config/encoding/testdata/v1alpha3/valid-many-fields.yaml
  pkg/internal/apis/config/encoding/testdata/v1alpha3/valid-minimal-two-nodes.yaml
  pkg/internal/apis/config/encoding/testdata/v1alpha3/valid-minimal.yaml
  pkg/internal/apis/config/encoding/testdata/v1alpha4/valid-many-fields.yaml
  pkg/internal/apis/config/types.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/XXL

#1589 [Podman] Fix volume mount options
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/internal/providers/podman/util.go
Labels: cncf-cla: yes, size/M

#1605 stop using IP auto detection
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1604 fix podman multinode clusters
  pkg/cluster/internal/providers/podman/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1602 Up version to 0.8.1 at quick-start.md
  README.md
  site/content/docs/user/quick-start.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#1610 disallow capitals in cluster names
  pkg/cluster/internal/create/create.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1597 bump to go 1.14.3
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1612 improved provider detection
  pkg/cluster/internal/providers/docker/util.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/util.go
  pkg/cluster/provider.go
Labels: cncf-cla: yes, size/M

#1595 Add support to configure kube-proxy mode
  pkg/apis/config/v1alpha4/default.go
  pkg/apis/config/v1alpha4/types.go
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/internal/apis/config/convert_v1alpha4.go
  pkg/internal/apis/config/default.go
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/validate.go
  pkg/internal/apis/config/validate_test.go
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1613 clean apt build type
  pkg/build/nodeimage/internal/kube/bits.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1585 Docs for using Ambassador as Ingress Controller
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1599 Upgrade containerd to 1.4-beta.0
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1630 use path package for container paths
  pkg/cluster/nodeutils/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1629 Update docs for WSL2
  site/content/docs/user/using-wsl2.md
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#1635 Rollback containerd
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/XS

#1627 trap INT and TERM in CI
  hack/ci/e2e-k8s.sh
  hack/ci/e2e.sh
Labels: approved, cncf-cla: yes, size/M

#1639 Do the same kind of cgroup fix also for podman
  images/base/files/usr/local/bin/entrypoint
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
