Repository kubernetes-sigs/kind, pull requests merged in 2020-08, with the labels that each got.

#1768 Make rules
  Makefile
  hack/make-rules/update/README.md
  hack/make-rules/update/all.sh
  hack/make-rules/update/deps.sh
  hack/make-rules/update/generated.sh
  hack/make-rules/update/gofmt.sh
  hack/make-rules/verify/README.md
  hack/make-rules/verify/all.sh
  hack/make-rules/verify/generated.sh
  hack/make-rules/verify/lint.sh
  hack/make-rules/verify/shellcheck.sh
Labels: approved, cncf-cla: yes, size/M

#1769 replace go_container.sh with gimme
  .go-version
  Makefile
  go.sum
  hack/build/setup-go.sh
  hack/ci/build-all.sh
  hack/go_container.sh
  hack/make-rules/unit.sh
  hack/make-rules/update/deps.sh
  hack/make-rules/update/generated.sh
  hack/make-rules/update/gofmt.sh
  hack/make-rules/verify/generated.sh
  hack/make-rules/verify/lint.sh
  hack/release/build/cross.sh
  hack/third_party/gimme/LICENSE
  hack/third_party/gimme/README.md
  hack/third_party/gimme/gimme
  hack/tools/go.sum
  images/kindnetd/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1770 add OWNERS for podman specific code
  pkg/cluster/internal/providers/docker/OWNERS
  pkg/cluster/internal/providers/podman/OWNERS
Labels: approved, area/provider/podman, cncf-cla: yes, lgtm, size/S

#1771 switch to go1.15rc2
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1764 Separate volumes for the different mounts.
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/internal/providers/podman/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1777 upgrade to go1.15
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1779 remove build-bash
  pkg/build/nodeimage/internal/kube/dockerbuildbits.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1782 rework build interfaces
  pkg/build/nodeimage/build.go
  pkg/build/nodeimage/build_impl.go
  pkg/build/nodeimage/installcontext.go
  pkg/build/nodeimage/internal/kube/bazelbuildbits.go
  pkg/build/nodeimage/internal/kube/bits.go
  pkg/build/nodeimage/internal/kube/builder.go
  pkg/build/nodeimage/internal/kube/builder_bazel.go
  pkg/build/nodeimage/internal/kube/builder_docker.go
  pkg/build/nodeimage/internal/kube/source.go
  pkg/build/nodeimage/internal/kube/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1784 Keeping up with packages
  go.mod
  go.sum
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1787 Containerd release 1.4
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1788 use /16 service subnet by default
  pkg/apis/config/v1alpha4/default.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1781 add podman ci
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/L

#1785 feat(docker/provider): defer to desktop.docker.io label for api endpoint, if present
  pkg/cluster/internal/providers/docker/provider.go
Labels: approved, area/provider/docker, cncf-cla: yes, lgtm, ok-to-test, size/S

#1793 add a note about go get inside go module projects
  README.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1794 disable podman failing job
  .github/workflows/podman.yml
Labels: cncf-cla: yes, lgtm, size/XS

#1795 Dockerfile: fix ubuntu version comment
  images/base/Dockerfile
Labels: cncf-cla: yes, ok-to-test, size/XS

#1796 Fix broken link in images/node
  images/node/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1798 Improve Dockerfile for base
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1804 tiny roadmap tweaks
  site/content/docs/contributing/1.0-roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1805 set providerID
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1809 unexport concrete provider implementation types, fix TODO
  pkg/cluster/internal/create/actions/action.go
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/create/actions/loadbalancer/loadbalancer.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/delete/delete.go
  pkg/cluster/internal/kubeconfig/kubeconfig.go
  pkg/cluster/internal/providers/common/constants.go
  pkg/cluster/internal/providers/common/doc.go
  pkg/cluster/internal/providers/common/getport.go
  pkg/cluster/internal/providers/common/getport_test.go
  pkg/cluster/internal/providers/common/images.go
  pkg/cluster/internal/providers/common/images_test.go
  pkg/cluster/internal/providers/common/logs.go
  pkg/cluster/internal/providers/common/namer.go
  pkg/cluster/internal/providers/common/namer_test.go
  pkg/cluster/internal/providers/common/proxy.go
  pkg/cluster/internal/providers/common/proxy_test.go
  pkg/cluster/internal/providers/docker/images.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/images.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/internal/providers/provider.go
  pkg/cluster/provider.go
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, size/L

#1810 Bump images
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/XS

#1811 retry kubeconfig export in kind create cluster
  pkg/cluster/internal/create/create.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1813 revert back to persisting all of /var
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provision.go
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, lgtm, size/S

#1814 move sleep to begining of retry loop
  pkg/cluster/internal/create/create.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1791 replaced user-guide link with quick-start-guide
  site/content/docs/_index.md
Labels: cncf-cla: yes, kind/documentation, ok-to-test, priority/backlog, size/S

#1815 bump cni plugins to 0.8.7
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1816 Runtime config
  hack/ci/e2e-k8s.sh
  hack/make-rules/update/generated.sh
  pkg/apis/config/v1alpha4/types.go
  pkg/apis/config/v1alpha4/zz_generated.deepcopy.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/internal/apis/config/convert_v1alpha4.go
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1817 automate collecting contributors
  hack/release/get-contributors.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1819 fix passing runtime_config
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, priority/critical-urgent, size/XS

#1820 add back runtimeConfig key
  hack/ci/e2e-k8s.sh
Labels: cncf-cla: yes, priority/critical-urgent

#1822 fixes for runtime-config & e2e
  hack/ci/e2e-k8s.sh
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS, ¯\_(ツ)_/¯

#1823 Fix problem with spaces in $PATH
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#1818 rework containerd config
  images/base/files/etc/containerd/config.toml
  images/base/files/usr/local/bin/entrypoint
  pkg/build/nodeimage/build_impl.go
  pkg/build/nodeimage/containerd_config.go
  pkg/build/nodeimage/defaults.go
  pkg/build/nodeimage/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1825 Modify kind-gcr.sh to prevent the use of credsStore
  site/static/examples/kind-gcr.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1827 ensure root owns binaries in node image
  pkg/build/nodeimage/build_impl.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
