Repository kubernetes-sigs/kind, pull requests merged in 2020-03, with the labels that each got.

#1378 Add GA_ONLY option to e2e-k8s script
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1346 Fix ctr image import error on ARM
  pkg/build/node/import.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1274 only set featuregates string if non empty
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1379 Config fixup
  pkg/cluster/internal/kubeadm/config.go
  pkg/cluster/internal/patch/matchinfo.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1380 add ci go caching script
  hack/ci/cache-wrapper.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1382 tweak CI build
  hack/ci/build-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1381 silence docker volume inspect
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1389 HONK
  site/content/docs/user/configuration.md
  site/layouts/shortcodes/securitygoose.html
  site/static/third_party/shiny_goose.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1390 s/KIND/kind in warning
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1394 fix base image build on macos
  images/base/Makefile
Labels: ¯\_(ツ)_/¯

#1395 fix buildx auto-init
  hack/build/init-buildx.sh
Labels: cncf-cla: yes

#1408 auto select iptables mode
  images/base/files/usr/local/bin/entrypoint
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1415 use output lines when getting IPs
  pkg/cluster/internal/providers/docker/node.go
  pkg/cluster/internal/providers/podman/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1414 embedded dns compatibility
  images/base/files/usr/local/bin/entrypoint
  pkg/build/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1421 IPv6 docker nat Known issue
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1426 bump to go 1.14.1
  hack/go_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1428 remove extra closing parenthesis
  site/content/docs/design/base-image.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1434 Fix typo
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1409 BUG: fix finding the provider when links are present
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/podman/provider.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1430 Fix hack/update/deps.sh for kindnetd code move
  hack/update/deps.sh
  images/kindnetd/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1431 Updated contributing doc to correct script names
  site/content/docs/contributing/project-structure.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1442 Fixes broken todo on roadmap page
  site/content/docs/contributing/1.0-roadmap.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1443 upgrade to json-patch v5
  go.mod
  go.sum
  pkg/cluster/internal/patch/json6902patch.go
  pkg/cluster/internal/patch/resource.go
  pkg/cluster/internal/patch/toml.go
Labels: approved, cncf-cla: yes, lgtm, size/S
