Repository kubernetes-sigs/kind, pull requests merged in 2021-05, with the labels that each got.

#2231 bump to go1.16.4
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2241 don't set conntrack parameters in kube-proxy
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2207 bump containerd and cri-tools to latest
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2176 support cross-compiling node-image
  hack/release/build/push-node.sh
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/build.go
  pkg/build/nodeimage/buildcontext.go
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
  pkg/build/nodeimage/defaults.go
  pkg/build/nodeimage/imageimporter.go
  pkg/build/nodeimage/internal/container/docker/archive.go
  pkg/build/nodeimage/internal/container/docker/pull.go
  pkg/build/nodeimage/internal/kube/builder_docker.go
  pkg/build/nodeimage/options.go
  pkg/cmd/kind/build/nodeimage/nodeimage.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2251 runc rc94 take two
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2253 cover upstream build requirements
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2255 possibly fix cross build
  hack/release/build/push-node.sh
  pkg/build/nodeimage/internal/kube/builder_docker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2259 Release 0.11.0
  pkg/cmd/kind/version/version.go
Labels: approved, area/provider/podman, cncf-cla: yes, lgtm, size/XS

#2245 Fetch the sha256 directly
  images/base/update-shasums.sh
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, ok-to-test, size/S

#2134 Update pause container
  images/base/files/etc/containerd/config.toml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2263 api: fix comment about ipvs mode
  pkg/apis/config/v1alpha4/types.go
  pkg/internal/apis/config/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2266 Updating README & docs to point for latest 0.11.0 release
  README.md
  site/config.toml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2269 update containerd to 1.5.2
  hack/release/build/push-node.sh
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2256 podman: make Info() robust
  pkg/cluster/internal/providers/podman/provider.go
Labels: approved, area/provider/podman, cncf-cla: yes, lgtm, ok-to-test, size/M

#2260 Add support for MacPorts installation.
  README.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2279 hack/ci/Vagrantfile: specify box_url explicitly
  hack/ci/Vagrantfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2285 podman resolve short name and update CI using fedora 34
  hack/ci/Vagrantfile
  pkg/cluster/internal/providers/podman/images.go
  pkg/cluster/internal/providers/podman/images_test.go
Labels: approved, area/provider/podman, cncf-cla: yes, lgtm, size/L

#2278 rootless: use fuse-overlayfs snapshotter by default
  images/base/Dockerfile
  images/base/files/etc/containerd/config.toml
  images/base/files/etc/systemd/system/containerd-fuse-overlayfs.service
  images/base/files/usr/local/bin/entrypoint
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provision.go
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, lgtm, ok-to-test, size/M
