Repository kubernetes-sigs/kind, pull requests merged in 2021-04, with the labels that each got.

#2173 Dual stack follow-ups
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/kubeadm/config.go
  site/content/docs/user/configuration.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2177 bump to go1.16.3
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2179 avoid head sigpipe
  images/base/files/usr/local/bin/entrypoint
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2192 docs: drop bazel
  README.md
  pkg/cmd/kind/build/nodeimage/nodeimage.go
  site/content/_index.md
  site/content/docs/user/known-issues.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2215 potential fix for white space in source path
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2225 make kindnetd tolerate everything
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2226 don't allow _ in cluster names
  pkg/internal/apis/config/validate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
