Repository kubernetes-sigs/kind, pull requests merged in 2021-01, with the labels that each got.

#2010 bump go to latest
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1995 Fix entrypoint cgroups mounts
  .github/workflows/docker.yaml
  images/base/files/usr/local/bin/entrypoint
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2011 bump node image
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1944 Prevent remote access to insecure registry
  site/static/examples/kind-with-registry.sh
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1948 images/base: disable udev.service
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, ok-to-test, size/XS

#1997 Spelling
  Makefile
  hack/ci/push-latest-cli/push-latest-cli.sh
  images/base/Dockerfile
  images/kindnetd/Dockerfile
  images/kindnetd/cmd/kindnetd/cni.go
  pkg/apis/config/v1alpha4/types.go
  pkg/build/nodeimage/build_impl.go
  pkg/cluster/internal/create/actions/installstorage/storage.go
  pkg/cluster/internal/create/actions/kubeadminit/init.go
  pkg/cluster/internal/create/actions/kubeadmjoin/join.go
  pkg/cluster/internal/create/actions/waitforready/waitforready.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/cluster/internal/kubeconfig/internal/kubeconfig/encode.go
  pkg/cluster/internal/kubeconfig/internal/kubeconfig/encode_test.go
  pkg/cluster/internal/kubeconfig/internal/kubeconfig/types.go
  pkg/cluster/internal/kubeconfig/kubeconfig.go
  pkg/cluster/internal/providers/common/proxy_test.go
  pkg/cluster/internal/providers/docker/network.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/podman/network.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/internal/apis/config/types.go
  site/content/docs/contributing/1.0-roadmap.md
  site/content/docs/contributing/getting-started.md
Labels: area/provider/docker, area/provider/podman, cncf-cla: yes, ok-to-test, size/M

#1973 bump CNI plugin to v0.9.0
  images/base/Dockerfile
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1996 document loadbalancer
  site/content/docs/user/configuration.md
  site/content/docs/user/loadbalancer.md
  site/content/docs/user/quick-start.md
  site/static/examples/loadbalancer/metallb-configmap.yaml
  site/static/examples/loadbalancer/usage.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2014 entrypoint: fix regression for cgroup v2
  images/base/files/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  images/base/files/usr/local/bin/create-kubelet-cgroup-v2
  images/base/files/usr/local/bin/entrypoint
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#2012 bump images
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2017 add cgroup2 CI
  .github/workflows/cgroup2.yaml
  .gitignore
  hack/ci/Vagrantfile
  hack/ci/vagrant-helper.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2025 promote amwat, aojea to full maintainer
  OWNERS
  README.md
  site/content/_index.md
  site/content/docs/contributing/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2022 don't redundantly run lints in github actions
  .github/workflows/docker.yaml
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2029 Mark release 0.10.0
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, size/XS

#2031 Update link to cncf.io
  README.md
  site/content/_index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2037 improve releasing instructions
  hack/release/create.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#2042 Updating README to point for latest 0.10.0 release
  README.md
  site/content/_index.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
