Repository kubernetes-sigs/kind, pull requests merged in 2021-02, with the labels that each got.

#2033 Added SHA256 checksums to node base image downloads
  hack/build/update-base-image-shasums.sh
  images/base/Dockerfile
  images/base/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2052 update to go 1.16rc1
  .go-version
  go.sum
  hack/tools/go.sum
  images/kindnetd/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2057 improve shasums handling, upgrade binary base-image deps
  hack/build/update-base-image-shasums.sh
  images/base/Dockerfile
  images/base/Makefile
  images/base/README.md
  images/base/update-shasums.sh
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1967 Move cluster name validation to Validate method
  pkg/cluster/internal/create/create.go
  pkg/internal/apis/config/validate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2060 retry vagrant up
  .github/workflows/cgroup2.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2059 set container env for podman nodes
  pkg/cluster/internal/providers/podman/provision.go
Labels: approved, area/provider/podman, cncf-cla: yes, lgtm, size/XS

#2028 Add docs for "Couldn't find an alternative telinit implementation to…
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2064 explicitly opt nodes out of tini
  pkg/cluster/internal/providers/docker/provision.go
Labels: approved, area/provider/docker, cncf-cla: yes, lgtm, size/XS

#2065 Update golang deps
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2066 Fix init-buildx.sh
  hack/build/init-buildx.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2068 fix goinstall shell
  hack/build/goinstalldir.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2071 try using preinstalled podman
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, size/XS

#2069 add public API to detect node providers
  pkg/cluster/provider.go
  pkg/errors/errors.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2073 use preinstalled podman
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2072 eliminate kubelet crashloop 🙃
  images/base/files/etc/systemd/system/kubelet.service
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2075 switch ci runners to ubuntu 20.04
  .github/workflows/docker.yaml
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2077 bump to go 1.16 release
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2079 Adding a note for extraMounts on Mac and Windows
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2043 kindnetd don't wait for kube-proxy
  images/kindnetd/Dockerfile
  images/kindnetd/README.md
  images/kindnetd/cmd/kindnetd/main.go
  pkg/build/nodeimage/const_cni.go
  pkg/cluster/internal/create/actions/installcni/cni.go
Labels: approved, cncf-cla: yes, size/L

#2084 Upgrade base deps
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/S

#2086 temporally use runc for podman ci
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2089 remove build type defaulting (CI jobs explicitly select this now)
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2091 Improve entrypoint cgroup handling
  images/base/files/usr/local/bin/entrypoint
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2092 explicitly set cgroupDriver
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/S

#2096 add darwin/arm64 to CLI build
  hack/release/build/cross.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2098 run apt-get update before apt-get install
  .github/workflows/cgroup2.yaml
  .github/workflows/podman.yml
Labels: approved, area/provider/podman, cncf-cla: yes, kind/failing-test, lgtm, size/XS
