Repository kubernetes-sigs/kind, pull requests merged in 2021-11, with the labels that each got.

#2522 Fix a golint issue caused by typo
  pkg/build/nodeimage/internal/container/docker/archive.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, ok-to-test

#2523 update dependencies / go version
  .go-version
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  images/kindnetd/Dockerfile
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/build/nodeimage/const_cni.go
Labels: approved, size/XXL, cncf-cla: yes, lgtm

#2505 fix(cgroupsv2): skip procs from another namespace
  images/base/files/usr/local/bin/create-kubelet-cgroup-v2
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2526 Bump containerd
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2511 podman-provider: get actually available cgroupControllers
  pkg/cluster/internal/providers/podman/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test, area/provider/podman

#2351 re-organize install guide and add more details
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2527 podman: use devicemapper for some filesystems
  pkg/cluster/internal/providers/podman/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M, area/provider/podman

#2497 Support getting all kind nodes with -A flag
  pkg/cmd/kind/get/nodes/nodes.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2539 assorted overdue cleanup
  OWNERS
  go.mod
  go.sum
  hack/make-rules/verify/lint.sh
  hack/tools/.golangci.yml
  pkg/build/nodeimage/buildcontext.go
  pkg/build/nodeimage/internal/kube/builder_docker.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/cluster/internal/kubeconfig/internal/kubeconfig/paths.go
  pkg/cluster/internal/providers/common/cgroups.go
  pkg/cluster/internal/providers/common/images.go
  pkg/cluster/internal/providers/common/images_test.go
  pkg/cluster/internal/providers/common/provision.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/internal/providers/podman/util.go
  pkg/errors/aggregate.go
  pkg/errors/aggregate_forked.go
  pkg/internal/sets/doc.go
  pkg/internal/sets/empty.go
  pkg/internal/sets/string.go
  pkg/internal/version/doc.go
  pkg/internal/version/version.go
  pkg/internal/version/version_test.go
Labels: approved, size/XXL, cncf-cla: yes, lgtm, area/provider/docker, area/provider/podman

#2536 kind load remove duplicate images names
  pkg/cmd/kind/load/docker-image/docker-image.go
  pkg/cmd/kind/load/docker-image/docker-image_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2544 Fix a small typo
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2546 set --snapshotter when loading image archives
  pkg/cluster/nodeutils/util.go
  pkg/cluster/nodeutils/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2547 upgrade to containerd 1.5.8
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2553 fix mount-product-files, bump deps / images
  .go-version
  images/base/files/usr/local/bin/mount-product-files
  images/kindnetd/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2531 Bumps kindnetd image and go version
  .go-version
  images/kindnetd/Dockerfile
Labels: cncf-cla: yes, size/XS, kind/cleanup, sig/testing, do-not-merge/hold, area/dependency, sig/security

#2554 de-dupe clusterHasIPv6 and clusterHasImplicitLoadBalancer in providers
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/internal/apis/config/cluster_util.go
  pkg/internal/apis/config/cluster_util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, area/provider/docker, area/provider/podman

#2558 fix dual-stack order detection
  pkg/cluster/internal/create/actions/config/config.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent
