Repository kubernetes-sigs/kind, pull requests merged in 2021-06, with the labels that each got.

#2294 Fix docs for shortcode about absURL
  site/content/docs/contributing/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2249 cgroup2 CI: add Rootless Docker/Podman provider
  .github/workflows/cgroup2.yaml
  hack/ci/Vagrantfile
  hack/ci/vagrant-helper.sh
Labels: approved, area/provider/podman, cncf-cla: yes, lgtm, ok-to-test, size/M

#2297 bump to go 1.16.5
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2218 implemented --internal on export kubeconfig
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/kubeconfig/kubeconfig.go
  pkg/cluster/provider.go
  pkg/cmd/kind/export/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2307 Tweaks 0.11.1
  README.md
  site/config.toml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2309 Use correct module names iptable_nat, ip6table_nat
  hack/ci/Vagrantfile
  site/content/docs/user/rootless.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2311 upgrade base images
  images/kindnetd/Dockerfile
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2310 reduce image sizes
  hack/release/build/push-node.sh
  images/base/Dockerfile
  images/base/files/usr/local/bin/clean-install
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2320 Revert bad entrypoint bash
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2301 Adds SCTP to comment of protocol in PortMapping
  pkg/apis/config/v1alpha4/types.go
  pkg/internal/apis/config/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2324 update qemu image to latest digest
  hack/build/init-buildx.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2330 Cross off ARM support from Roadmap
  site/content/docs/contributing/1.0-roadmap.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2329 Update description for verbosity
  pkg/cmd/kind/root.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#2337 Added docs for service with SessionAffinity in WSL
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2338 update kind version for macOS in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2340 add known issue for Fedora 33 SELinux
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2341 aggregate fedora known issues
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2336 feat: add sha256sums for kind binaries
  hack/release/build/cross.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#2342 bump kindnetd deps and remove pkg/errors dep
  images/kindnetd/Dockerfile
  images/kindnetd/cmd/kindnetd/cni.go
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2289 match https://github.com/kubernetes-sigs/iptables-wrappers/blob/maste…
  images/base/files/usr/local/bin/entrypoint
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S
