Repository kubernetes-sigs/kind, pull requests merged in 2021-07, with the labels that each got.

#2344 bump node image
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2306 Update ingress from v1beta1 to v1
  site/static/examples/ingress/usage.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2347 Change Ingress NGINX script to use stable version
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2345 upgrade direct dependencies, drop unnecessary requirement on x/sys
  go.mod
  go.sum
  pkg/cluster/internal/patch/toml_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2350 switch to qemu v6 image
  hack/build/init-buildx.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2355 Clean up extra spaces
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2354 Fix `container` envvar and StopSignal are not set in kindest/node:v1.21.2
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2358 Update api doc redirects
  site/data/apiVersions.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2363 bump go to 1.16.6
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2367 CI: fix Fedora 34 VM
  .github/workflows/cgroup2.yaml
  hack/ci/Vagrantfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2368 Use main branch as the stable branch in Ingress demo
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2373 Distroless haproxy
  images/Makefile.common.in
  images/haproxy/Dockerfile
  images/haproxy/stage-binary-and-deps.sh
  pkg/cluster/internal/loadbalancer/const.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2364 Cli: add the cluster name to the error message
  pkg/cluster/internal/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2335 added json coverage for scheduler
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#2380 Add doc for optional parameters on extraMounts
  site/static/examples/config-with-mounts.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2359 Remove vendor part in make clean
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#2382 check if containerd is running not if system is running
  pkg/cluster/internal/create/actions/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2386 upgrade base image + deps, support containerd-fuse-overlayfs in update-shasums
  images/base/Dockerfile
  images/base/update-shasums.sh
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2389 Add depricated comment for kube-root flag to build node-image help
  pkg/cmd/kind/build/nodeimage/nodeimage.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2391 Update node image build source reference
  images/node/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2393 change http to https websites
  site/content/_index.md
  site/content/docs/contributing/getting-started.md
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2397 update to containerd v1.5.5
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2375 enable sysctl route_localnet
  images/base/files/etc/sysctl.d/10-network-magic.conf
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2398 DRY out kindnetd image and bump it to latest build
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2387 Add ability to specify log format for componentManager and apiServer.
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
