Repository kubernetes-sigs/kind, pull requests merged in 2021-03, with the labels that each got.

#2090 Exit with non-zero codes when user input is invalid
  cmd/kind/app/main_test.go
  pkg/cmd/kind/build/build.go
  pkg/cmd/kind/completion/completion.go
  pkg/cmd/kind/create/create.go
  pkg/cmd/kind/delete/delete.go
  pkg/cmd/kind/export/export.go
  pkg/cmd/kind/get/get.go
  pkg/cmd/kind/load/load.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2102 stop setting providerless/dockerless tags by default
  hack/release/build/push-node.sh
  pkg/build/nodeimage/internal/kube/builder_docker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2104 switch all CI to make
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2107 Revert "use runc for podman ci"
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2088 Add possibility to disable kube-proxy
  pkg/apis/config/v1alpha4/default.go
  pkg/apis/config/v1alpha4/types.go
  pkg/cluster/internal/create/actions/kubeadminit/init.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/internal/apis/config/default.go
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/validate.go
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2110 Fix "Page Not Found" link about relative path
  site/content/docs/user/configuration.md
  site/content/docs/user/loadbalancer.md
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1935 Support Rootless Docker and Rootless Podman, without patching Kubernetes
  images/base/files/etc/containerd/config.toml
  images/base/files/usr/local/bin/entrypoint
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/provider.go
  site/content/docs/user/rootless.md
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, lgtm, ok-to-test, size/L

#2116 Upgrade base image
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2062 update pause image to 3.4.1
  images/base/files/etc/containerd/config.toml
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2117 upgrade to go1.16.1
  .go-version
Labels: approved, cncf-cla: yes, size/XS

#2119 update node image to latest
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, size/XS

#2097 speed up kubernetes builds
  pkg/build/nodeimage/internal/kube/builder_docker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2123 add ability to enable kubelet structured logging in CI
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2124 upgrade to go1.16.2
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2122 podman: mount dev mapper for btrfs and zfs storage
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/internal/providers/podman/util.go
Labels: approved, area/provider/podman, cncf-cla: yes, lgtm, size/S

#1926 added: support for adding labels from the config file itself
  pkg/apis/config/v1alpha4/types.go
  pkg/apis/config/v1alpha4/zz_generated.deepcopy.go
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/internal/apis/config/convert_v1alpha4.go
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/M

#2103 Add Documentation for Cluster Name via Yaml Configuration
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2130 Link Go struct godoc for Cluster type
  site/content/docs/user/configuration.md
Labels: cncf-cla: yes, lgtm, size/XS

#2121 reduce node CRI disk usage
  images/base/files/etc/containerd/config.toml
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2131 base: config.toml: fix "snapshotter" location
  images/base/files/etc/containerd/config.toml
Labels: approved, lgtm, ok-to-test, size/XS

#2132 bump base image
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/XS

#2128 create control plane containers with `-e KUBECONFIG=/etc/kubernetes/admin.conf`
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provision.go
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, lgtm, ok-to-test, size/S

#2133 build cleanup: drop bazel
  hack/ci/e2e-k8s.sh
  pkg/build/nodeimage/build.go
  pkg/build/nodeimage/defaults.go
  pkg/build/nodeimage/internal/kube/builder.go
  pkg/build/nodeimage/internal/kube/builder_bazel.go
  pkg/build/nodeimage/options.go
  pkg/cmd/kind/build/nodeimage/nodeimage.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1920 issue 1905/support for multiple images to kind load
  pkg/cmd/kind/load/docker-image/docker-image.go
  site/content/docs/user/quick-start.md
Labels: cncf-cla: yes, ok-to-test, size/M

#2135 fix minor formatting nit
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, size/XS

#2125 Add a shortcode for inserting the stable version
  site/config.toml
  site/content/_index.md
  site/content/docs/user/quick-start.md
  site/layouts/shortcodes/stableVersion.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#2137 update references to kind master branch -> main branch
  .github/workflows/cgroup2.yaml
  .github/workflows/docker.yaml
  .github/workflows/podman.yml
  hack/ci/cache-wrapper.sh
  site/content/_index.md
  site/content/docs/design/initial.md
  site/content/docs/design/principles.md
  site/content/docs/user/quick-start.md
  site/content/docs/user/working-offline.md
  site/layouts/partials/footer.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#2139 Copy scripts and configs separately during base image build
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2140 Add cgroups v2 support to known issues
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/S

#2145 actually support merge patches with document streams
  hack/ci/e2e-k8s.sh
  pkg/cluster/internal/patch/kubeyaml_test.go
  pkg/cluster/internal/patch/mergepatch.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#2146 correctly generate newline in e2e-k8s.sh
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, size/XS

#2147 try again generating newline
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, size/XS

#2149 detect docker btrfs backend filesystem
  pkg/cluster/internal/providers/docker/util.go
Labels: approved, area/provider/docker, cncf-cla: yes, lgtm, size/M

#2144 restore podman portmap check for 3.0.0+
  .github/workflows/podman.yml
  pkg/cluster/internal/providers/podman/provider.go
Labels: approved, area/provider/podman, cncf-cla: yes, lgtm, size/L

#2154 fix: fix broken download links
  site/layouts/shortcodes/stableVersion.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2129 rootless: fail early if prerequiresites are not satisfied
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/provider.go
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, lgtm, ok-to-test, size/L

#2155 doc: add kubeadm ClusterConfiguration spec usage.
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2153 use docker0 mtu for kind network
  pkg/cluster/internal/providers/docker/network.go
Labels: approved, area/provider/docker, cncf-cla: yes, lgtm, size/M

#2161 fix kind export logs
  pkg/cluster/internal/providers/common/logs.go
  pkg/cluster/provider.go
  pkg/cmd/kind/export/logs/logs.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#692 Add dual stack support
  images/kindnetd/Dockerfile
  images/kindnetd/cmd/kindnetd/cni.go
  images/kindnetd/cmd/kindnetd/main.go
  images/kindnetd/cmd/kindnetd/routes.go
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/apis/config/v1alpha4/default.go
  pkg/apis/config/v1alpha4/types.go
  pkg/build/nodeimage/const_cni.go
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/internal/apis/config/default.go
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/validate.go
  pkg/internal/apis/config/validate_test.go
  site/content/docs/user/quick-start.md
Labels: approved, area/provider/docker, area/provider/podman, cncf-cla: yes, lgtm, priority/important-soon, size/XL

#2162 update containerd, base
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2165 don't use loopback addresses on the nodes resolv.conf file
  images/base/files/usr/local/bin/entrypoint
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
