Repository kubernetes-sigs/kind, pull requests merged in 2022-12, with the labels that each got.

#3027 upgrade base + node image
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3013 load docker-image: only use sanitized name for retagging
  pkg/cmd/kind/load/docker-image/docker-image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3025 docs: fix usage.yaml in ingress user guide
  site/content/docs/user/ingress.md
  site/static/examples/ingress/usage.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#3032 clarify bug template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3036 Upgrade to containerd 1.6.14
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3037 images/haproxy: overwrite instead of concatenating dpkg status
  images/haproxy/stage-binary-and-deps.sh
  pkg/cluster/internal/loadbalancer/const.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
