Repository kubernetes-sigs/kind, pull requests merged in 2022-02, with the labels that each got.

#2619 only mount /dev/fuse for rootless
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/S, area/provider/docker, area/provider/podman

#2621 Local registry example uses port 5001 to be more mac friendly
  site/content/docs/user/local-registry.md
  site/static/examples/kind-with-registry.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#2584 Document known issue around BTRFS
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2624 stage dpkg status, upgrade haproxy image to debian11
  images/haproxy/Dockerfile
  images/haproxy/stage-binary-and-deps.sh
  pkg/cluster/internal/loadbalancer/const.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2620 only mount /dev/fuse for rootless
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/docker/util.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/cluster/internal/providers/podman/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M, area/provider/docker, area/provider/podman

#2647 Skip GitHub Actions on doc only changes
  .github/workflows/cgroup2.yaml
  .github/workflows/docker.yaml
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
