Repository kubernetes-sigs/kind, pull requests merged in 2022-03, with the labels that each got.

#2651 Remove obsolete step from metallb guide
  site/content/docs/user/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2646 Add note to quick start about idempotent deletes
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2656 podman: don't try to delete without volumes
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/podman/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, area/provider/podman

#2658 update base image
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2653 bump go to 1.17.8
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2650 pkg/build: improve source finding message
  pkg/build/nodeimage/internal/kube/source.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2661 bump default node image
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2649 Release v0.12.0
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2666 update banner to support humanitarian aid for ukraine
  site/assets/css/inline.css
  site/layouts/partials/navbar.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#2660 updated doc for known issues
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2672 issue #2669: improve note visibility
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2676 docs(READEME): update kind version
  README.md
  site/config.toml
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#2679 Dump images used by kind into a log file
  pkg/cluster/internal/providers/common/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2682 docs: revert description
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2690 Add workarounds for Docker Desktop cgroupv2
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2691 update packages
  .go-version
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  images/base/Dockerfile
  images/base/update-shasums.sh
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2693 Moves the documentation of setting node images to Per-Node Options
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test
