Repository kubernetes-sigs/kind, pull requests merged in 2022-05, with the labels that each got.

#2742 mark /vagrant safe
  hack/ci/Vagrantfile
Labels: approved, cncf-cla: yes, size/XS

#2743 allow no matches when grepping for unsupported_cgroups
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2737 Use systemd cgroup driver for v1.24.0+
  images/base/Dockerfile
  images/base/files/etc/containerd/config.toml
  images/base/files/etc/systemd/system/kubelet.service
  images/base/files/usr/local/bin/create-kubelet-cgroup-v2
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/buildcontext.go
  pkg/build/nodeimage/containerd.go
  pkg/build/nodeimage/defaults.go
  pkg/build/nodeimage/helpers.go
  pkg/cluster/internal/create/actions/config/config.go
  pkg/cluster/internal/create/actions/installcni/cni.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/internal/patch/doc.go
  pkg/internal/patch/json6902patch.go
  pkg/internal/patch/kubeyaml.go
  pkg/internal/patch/kubeyaml_test.go
  pkg/internal/patch/matchinfo.go
  pkg/internal/patch/mergepatch.go
  pkg/internal/patch/resource.go
  pkg/internal/patch/toml.go
  pkg/internal/patch/toml_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2746 mark v0.13.0
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, size/XS

#2747 upgrade to go 1.18.2
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2753 update install directions for v0.13.0
  README.md
  site/config.toml
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2756 image load digests
  pkg/build/nodeimage/imageimporter.go
  pkg/cluster/nodeutils/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2750 bump haproxy
  images/haproxy/Dockerfile
  pkg/cluster/internal/loadbalancer/const.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2752 bump qemu to latest
  hack/build/init-buildx.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2749 Upgrade kindnetd
  images/kindnetd/Dockerfile
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2751 upgrade crictl to 1.24.0
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2761 just export logs into artifacts directly
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2764 move some flags into kubelet config
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2768 make registry configurable in push-node.sh
  hack/release/build/push-node.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#2773 Fix kong ingress name in documentation
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2777 kubeadminit: handle the "control-plane" taint for 1.25-pre
  pkg/cluster/internal/create/actions/kubeadminit/init.go
Labels: approved, cncf-cla: yes, lgtm, kind/cleanup, size/S

#2767 entrypoint cleanup + non-systemd-host fix
  images/base/files/etc/systemd/system/kubelet.service
  images/base/files/etc/systemd/system/kubelet.slice
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2779 use precise versions for kubeadm label / taint changes
  pkg/cluster/internal/create/actions/kubeadminit/init.go
  pkg/cluster/internal/create/actions/waitforready/waitforready.go
Labels: approved, size/XS

#2780 mark release v0.14.0
  README.md
  pkg/cmd/kind/version/version.go
  site/config.toml
Labels: approved, cncf-cla: yes, size/S

#2781 add missing link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2588 Fix broken link in known issues
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2775 Fix multi-node cluster not working after restarting docker
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2787 Update yaml library for CVE
  go.mod
  go.sum
  hack/make-rules/update/deps.sh
  hack/tools/go.mod
  hack/tools/go.sum
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/const_cni.go
  pkg/cluster/internal/providers/docker/network_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, area/provider/docker
