Repository kubernetes-sigs/kind, pull requests merged in 2022-10, with the labels that each got.

#2946 kindnetd fix removal of wrong routes
  images/kindnetd/cmd/kindnetd/routes.go
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2911 switch to safetext/yamltemplate for yaml templating
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/installcni/cni.go
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2956 upgrade to go version 1.19.2
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2950 Consider Docker Desktop for Linux
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test

#2955 Fix load docker-image re-tagging with prefix
  pkg/cmd/kind/load/docker-image/docker-image.go
  pkg/cmd/kind/load/docker-image/docker-image_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2957 Add --all-platforms flag to LoadImageArchive so that images are not filtered out by ctr
  pkg/cluster/nodeutils/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2966 docs: Add Docker in WSL2 without Docker Desktop
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test

#2973 Suggest in the documentation to wait until the MetalLB controller pod is ready
  site/content/docs/user/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#2974 steer users away from mount propagation
  site/static/examples/config-with-mounts.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2977 Upgrade containerd 1.6.9
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/S

#2969 Add unit tests for version command
  pkg/cmd/kind/version/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2894 doc: refactor copy to clipboard button
  site/assets/css/inline.css
  site/layouts/shortcodes/codeFromFile.html
  site/layouts/shortcodes/codeFromInline.html
  site/static/copycode.svg
Labels: approved, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash, ok-to-test

#2980 mark release v0.17.0
  README.md
  pkg/cmd/kind/version/version.go
  site/config.toml
Labels: approved, cncf-cla: yes, size/S

#2982 fix kind version in readme
  README.md
Labels: approved, cncf-cla: yes

#2986 comments-update-buildcontext
  pkg/build/nodeimage/buildcontext.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test
