Repository kubernetes-sigs/kind, pull requests merged in 2022-04, with the labels that each got.

#2711 Add ppc64le support
  images/Makefile.common.in
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2703 fix todo: remove docs/_index.md, now that we have navigation
  site/content/docs/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2709 entrypoint: fix chicken-and-egg runtime problem
  images/base/files/usr/local/bin/entrypoint
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2716 consider prereleases on comparisons
  pkg/cluster/internal/create/actions/kubeadminit/init.go
  pkg/internal/version/version_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/M

#2719 Prefer to build Ginkgo V2
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test
