Repository kubernetes-sigs/kind, pull requests merged in 2022-01, with the labels that each got.

#2575 fix: listnodes error message
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/podman/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, area/provider/docker, area/provider/podman

#2580 bump go to 1.17.6
  .go-version
Labels: approved, cncf-cla: yes, size/XS

#2581 bump containerd to 1.5.9
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2568 refactor: remove deprecated flag --address from scheduler config
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2582 upgrade to kubeadm v1beta3 config format
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2591 Point broken links to live ad-free file permissions calculator
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2595 handle "master" label/taint changes for kubeadm 1.24
  pkg/build/nodeimage/const_storage.go
  pkg/cluster/internal/create/actions/kubeadminit/init.go
  pkg/cluster/internal/create/actions/waitforready/waitforready.go
  site/static/examples/ingress/contour/patch.json
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/M, kind/deprecation

#2601 Local registry: only attach network if missing
  site/static/examples/kind-with-registry.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2602 minor follow-up tweaks to kind-with-registry.sh
  site/static/examples/kind-with-registry.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#2607 fix: typo and a wrong comment
  pkg/cluster/internal/providers/docker/network.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, area/provider/docker

#2603 added Kong ingress example
  site/content/docs/user/ingress.md
  site/static/examples/ingress/kong/deployment.patch.json
  site/static/examples/ingress/kong/service.patch.json
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test
