Repository kubernetes-sigs/kind, pull requests merged in 2022-08, with the labels that each got.

#2825 Fix KubeletConfiguration template for k8s < 1.15
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2847 CI: bump up macos-10.15 to macos-12
  .github/workflows/cgroup2.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2850 increase vagrant allocation
  hack/ci/Vagrantfile
Labels: approved, cncf-cla: yes, size/XS

#2853 improve image pushing script
  hack/release/build/push-node.sh
Labels: approved, cncf-cla: yes, size/XS

#2854 fix image tagging
  hack/release/build/push-node.sh
Labels: cncf-cla: yes

#2786 GIT-2663: optimized image load with re-tag support
  pkg/cluster/nodeutils/util.go
  pkg/cmd/kind/load/docker-image/docker-image.go
  pkg/cmd/kind/load/docker-image/docker-image_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test, area/provider/podman

#2846 disable localStorageCapacityIsolation for rootless in >= v1.25.0-alpha.3.440+0064010cddfa00
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2859 Updates linux default installation
  README.md
  site/content/docs/user/quick-start.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/XS, ok-to-test

#2861 simplify template
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2705 Set permissions for GitHub actions
  .github/workflows/cgroup2.yaml
  .github/workflows/docker.yaml
  .github/workflows/podman.yml
Labels: cncf-cla: yes, size/XS, ok-to-test

#2622 Distinguish usage of local registry for cluster and in-cluster app.
  site/content/docs/user/local-registry.md
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test

#2869 bump to containerd 1.6.7, go 1.19
  .go-version
  hack/tools/.golangci.yml
  images/base/Dockerfile
  images/kindnetd/cmd/kindnetd/cni.go
  pkg/apis/config/defaults/image.go
  pkg/apis/config/v1alpha4/types.go
  pkg/build/nodeimage/defaults.go
  pkg/build/nodeimage/internal/container/docker/image.go
  pkg/cluster/internal/create/actions/waitforready/waitforready.go
  pkg/cluster/internal/kubeconfig/internal/kubeconfig/paths.go
  pkg/internal/apis/config/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2818 Add single letter flag for names
  pkg/cmd/kind/build/nodeimage/nodeimage.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/cmd/kind/delete/cluster/deletecluster.go
  pkg/cmd/kind/delete/clusters/deleteclusters.go
  pkg/cmd/kind/delete/delete.go
  pkg/cmd/kind/export/kubeconfig/kubeconfig.go
  pkg/cmd/kind/export/logs/logs.go
  pkg/cmd/kind/get/kubeconfig/kubeconfig.go
  pkg/cmd/kind/get/nodes/nodes.go
  pkg/cmd/kind/load/docker-image/docker-image.go
  pkg/cmd/kind/load/image-archive/image-archive.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#2876 doc: fix kong ingress https port
  site/static/examples/ingress/kong/deployment.patch.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2883 Support for netavark backed podman(4.x+) - fixing #2882
  pkg/cluster/internal/providers/podman/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test, area/provider/podman

#2874 rework snapshotter selection, detect fuseblk and use overlayfs-fuse
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2877 Add extra labels section for per-node options
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-ok-to-test

#2885 Extending the no_proxy env variable to automatically include all the nodes of the cluster
  pkg/cluster/internal/providers/podman/provision.go
Labels: approved, cncf-cla: yes, lgtm, size/S, tide/merge-method-squash, ok-to-test, area/provider/docker, area/provider/podman
