Repository kubernetes-sigs/kind, pull requests merged in 2022-07, with the labels that each got.

#2820 cgroup2 CI: enable SELinux again
  .github/workflows/cgroup2.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2823 Update types.go
  pkg/apis/config/v1alpha4/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test

#2838 Base image to ubuntu 22.04
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2841 Distroless iptables
  images/kindnetd/Dockerfile
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2831 Add field tags for JSON (un)marshalling
  pkg/apis/config/v1alpha4/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2844 update to use go1.18.4
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS
