Repository kubernetes-sigs/kind, pull requests merged in 2022-06, with the labels that each got.

#2788 Add known issue "Docker Desktop for macOS and Windows"
  site/content/docs/user/known-issues.md
  site/content/docs/user/resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2790 upgrade go to 1.18.3
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2795 upgrade kubernetes debian images
  images/haproxy/Dockerfile
  images/kindnetd/Dockerfile
  images/local-path-helper/Dockerfile
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
  pkg/cluster/internal/loadbalancer/const.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2796 add timeout when attempt to resolve domain
  images/base/files/usr/local/bin/entrypoint
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2802 clarify the impact of Delegate=true when using rootless
  site/content/docs/user/rootless.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2810 Add resouce for developing k8s with Kind on Gitlab
  site/content/docs/user/resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2809 update pause to use v3.7
  images/base/files/etc/containerd/config.toml
  images/haproxy/Dockerfile
  images/kindnetd/Dockerfile
  images/local-path-helper/Dockerfile
  pkg/build/nodeimage/defaults.go
  pkg/cluster/nodeutils/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2811 upgrade containerd to v1.6.6
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S
