Repository kubernetes-sigs/kind, pull requests merged in 2022-09, with the labels that each got.

#2902 mark release v0.15.0
  hack/release/create.sh
  pkg/apis/config/defaults/image.go
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, size/XS

#2903 update docs to point to v0.15.0
  README.md
  site/config.toml
Labels: cncf-cla: yes

#2908 emeritus munnerz and amwat
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#2907 support not setting GITHUB_OAUTH_TOKEN
  hack/release/get-contributors.sh
Labels: approved, cncf-cla: yes, size/XS

#2909 update to go 1.19.1
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2914 alphabetize maintainers and drop inactive
  README.md
  site/content/_index.md
  site/content/docs/contributing/getting-started.md
Labels: approved, cncf-cla: yes

#2912 Drop support for Kubernetes < 1.15
  pkg/build/nodeimage/buildcontext.go
  pkg/cluster/internal/kubeadm/config.go
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2901 Suggest a more updated metallb version
  site/content/docs/user/loadbalancer.md
  site/static/examples/loadbalancer/metallb-config.yaml
  site/static/examples/loadbalancer/metallb-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2919 Remove Ambassador ingress docs
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2905 install open-iscsi
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2913 don't symlink /dev/console to /dev/kmsg
  images/base/files/usr/local/bin/entrypoint
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/S

#2935 Bump base deps
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2921 doc: alternative for port mapping or ingress
  site/content/docs/user/using-wsl2.md
Labels: cncf-cla: yes, size/XS, ok-to-test

#2936 bump node image to 1.25.2
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2910 check for new podman overlap error message
  pkg/cluster/internal/providers/podman/network.go
Labels: approved, cncf-cla: yes, lgtm, size/S, area/provider/podman

#2937 mark release v0.16
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes

#2940 doc: readme 0.16
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#2943 bump site to 0.16.0
  site/config.toml
Labels: cncf-cla: yes

#2941 kindnetd remove wrong routes
  images/kindnetd/cmd/kindnetd/routes.go
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/S
