Repository kubernetes-sigs/kind, pull requests merged in 2023-06, with the labels that each got.

#3263 add command to get podman subnet
  site/content/docs/user/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3264 Remove `-sf 7` from haproxy image entrypoint
  images/haproxy/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3273 update haproxy image to latest build
  pkg/cluster/internal/loadbalancer/const.go
Labels: approved, cncf-cla: yes, size/XS

#3274 upgrade to 1.27.3
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, size/XS

#3275 mark release v0.20.0
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes

#3276 update install to 0.20.0
  README.md
  site/config.toml
Labels: approved, cncf-cla: yes, size/S
