Repository kubernetes-sigs/kind, pull requests merged in 2023-04, with the labels that each got.

#3158 fix error notes for Provider package
  pkg/cluster/internal/providers/provider.go
  pkg/cluster/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3159 bump haproxy image
  pkg/cluster/internal/loadbalancer/const.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3162 use ctr content fetch and capture errors
  pkg/build/nodeimage/buildcontext.go
  pkg/build/nodeimage/imageimporter.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3023 e2e-k8s.sh: support alpha features
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#3172 ci: hack/release/get-contributors.sh: Fix incorrect token identification
  hack/release/get-contributors.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2992 Make changes in documentation
  site/content/docs/user/configuration.md
Labels: cncf-cla: yes, size/XS

#3177 don't use digests for preloaded images
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3178 use dnsSearch in CI
  hack/ci/e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3184 podman: create ipv4 network if ipv6 is disabled
  pkg/cluster/internal/providers/podman/network.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, area/provider/podman

#3185 update runc to 1.1.6 / update containerd
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#3186 don't build kindnetd image in build job
  hack/ci/build-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3183 doc: fix wrong implementation of creation of kong-ingress
  site/content/docs/user/ingress.md
  site/static/examples/ingress/kong/deployment.patch.json
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test

#3175 Raise error if host-ports are configured again with same listen address and protocol
  pkg/internal/apis/config/validate.go
  pkg/internal/apis/config/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, area/provider/docker
