Repository kubernetes-sigs/kind, pull requests merged in 2023-03, with the labels that each got.

#3115 fix: Limit HAProxy maximum concurrent connections
  images/haproxy/haproxy.cfg
  pkg/cluster/internal/loadbalancer/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3119 Update Vagrantfile
  hack/ci/Vagrantfile
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#3121 add minimum viable iptables fix from https://github.com/kubernetes/mi…
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3122 remove registry mirror config
  images/base/files/etc/containerd/config.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3108 Update during image build to get security patches
  images/base/files/usr/local/bin/clean-install
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3125 Add automated builds configs for most images
  images/Makefile.common.in
  images/base/cloudbuild.yaml
  images/haproxy/cloudbuild.yaml
  images/kindnetd/cloudbuild.yaml
  images/local-path-helper/cloudbuild.yaml
  images/local-path-provisioner/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3126 fix cloudbuild configs
  images/base/cloudbuild.yaml
  images/haproxy/cloudbuild.yaml
  images/kindnetd/cloudbuild.yaml
  images/local-path-helper/cloudbuild.yaml
  images/local-path-provisioner/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3129 drop platforms we cannot test (s390x, ppc64le)
  hack/release/build/cross.sh
  images/Makefile.common.in
  images/base/Dockerfile
  images/base/update-shasums.sh
  pkg/build/nodeimage/build.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3123 Clarify use of mounts for merge patches
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2934 Improve log output for delete cluster
  pkg/cluster/internal/delete/delete.go
Labels: approved, cncf-cla: yes, lgtm, size/S, tide/merge-method-squash, ok-to-test

#3136 Terminate codeFromInline block on the configuration page
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test

#3142 update containerd / runc / crictl
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#3143 bump kindnetd dependencies
  images/kindnetd/go.mod
  images/kindnetd/go.sum
Labels: approved, cncf-cla: yes, size/L

#3144 update to latest base image
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/XS

#3146 increase machine size for auto-builds
  images/base/cloudbuild.yaml
  images/kindnetd/cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/XS

#3090 upgrade local-path-provisioner
  images/local-path-provisioner/Makefile
Labels: cncf-cla: yes, size/XS, ok-to-test

#3147 improve post merge image builds
  images/haproxy/cloudbuild.yaml
  images/kindnetd/Dockerfile
  images/kindnetd/cloudbuild.yaml
  images/local-path-helper/cloudbuild.yaml
  images/local-path-provisioner/cloudbuild.yaml
Labels: cncf-cla: yes

#3148 upgrade kindnetd and storage provisioner to latest images
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
Labels: approved, cncf-cla: yes, size/XS

#3149 fix multi-arch builds
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes

#3150 update to v1.26.3
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, size/XS

#3137 Documented default pod and service subnets
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3151 bump main binary to 1.20.2
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3152 mark release v0.18.0
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, size/XS

#3153 update install for v0.18.0
  README.md
  site/config.toml
Labels: approved, cncf-cla: yes

#3154 user cheaper e2 vm type
  images/base/cloudbuild.yaml
  images/haproxy/cloudbuild.yaml
  images/kindnetd/cloudbuild.yaml
  images/local-path-helper/cloudbuild.yaml
  images/local-path-provisioner/cloudbuild.yaml
Labels: approved, cncf-cla: yes

#3156 Added platform flag to docker command in site Makefile
  site/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test

#3155 cleanup base image a bit
  images/base/Dockerfile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S
