Repository kubernetes-sigs/kind, pull requests merged in 2023-02, with the labels that each got.

#3085 Update deprecated github actions
  .github/workflows/cgroup2.yaml
  .github/workflows/docker.yaml
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#3091 test: update image registry from k8s.gcr.io to registry.k8s.io
  pkg/build/nodeimage/internal/container/docker/image_test.go
  pkg/cmd/kind/load/docker-image/docker-image_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#3099 kindnet: add nodeSelector
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3101 ChromeOS needs KubeletInUserNamespace
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#3107 Bump debian-base build image to v1.4.3
  images/haproxy/Dockerfile
  images/local-path-helper/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3098 Add `dnsSearch` cluster option
  images/base/files/usr/local/bin/entrypoint
  pkg/apis/config/v1alpha4/types.go
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/internal/apis/config/convert_v1alpha4.go
  pkg/internal/apis/config/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S, area/provider/docker, area/provider/podman

#3112 Bump dependencies
  .go-version
  hack/tools/go.mod
  hack/tools/go.sum
  images/base/Dockerfile
  pkg/apis/config/v1alpha4/zz_generated.deepcopy.go
  pkg/build/nodeimage/defaults.go
  pkg/internal/apis/config/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3113 Keep updating images
  images/kindnetd/Dockerfile
  images/local-path-provisioner/Dockerfile
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
  pkg/cluster/internal/loadbalancer/const.go
Labels: approved, cncf-cla: yes, lgtm, size/S
