Repository kubernetes-sigs/kind, pull requests merged in 2024-12, with the labels that each got.

#3716 cleanup long-deprecated flags
  pkg/cmd/kind/build/nodeimage/nodeimage.go
  pkg/cmd/kind/root.go
  site/content/docs/user/known-issues.md
  site/content/docs/user/working-offline.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3815 add fallback version detection for tarballs < v1.31
  pkg/build/nodeimage/internal/kube/builder_remote.go
  pkg/build/nodeimage/internal/kube/builder_tarball.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3784 Add note to configuration about HA control plane
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3816 upgrade base image and tooling dependencies
  .go-version
  hack/make-rules/update/generated.sh
  hack/tools/.golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
  images/base/Dockerfile
Labels: approved, size/XXL, cncf-cla: yes, lgtm

#3818 more upgrades for v0.26.0
  images/local-path-provisioner/Makefile
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3820 fix local-path-provisioner build
  images/local-path-provisioner/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3821 use latest kindnetd image build
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3819 update local-path-provisioner
  pkg/build/nodeimage/const_storage.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3824 update default node image to 1.32 with upgraded containerd etc
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3827 mark v0.26.0
  README.md
  pkg/cmd/kind/version/version.go
  site/config.toml
Labels: approved, cncf-cla: yes, size/S

#3814 fix `kind get clusters` via nerdctl
  pkg/cluster/internal/providers/nerdctl/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test
