Repository kubernetes-sigs/kind, pull requests merged in 2024-05, with the labels that each got.

#3597 [Chore] Change TEMPDIR to TMPDIR
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3599 fix kind version unit test failures for released versions
  pkg/cmd/kind/version/version.go
  pkg/cmd/kind/version/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-ok-to-test

#3607 upgrade to go1.21.10
  .go-version
Labels: approved, cncf-cla: yes, size/XS

#3608 Bump kindnetd mod
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3610 Mark v0.23.0
  README.md
  pkg/cmd/kind/version/version.go
  site/config.toml
Labels: approved, cncf-cla: yes

#3561 ci/dependabot updates
  .github/dependabot.yml
  .github/workflows/docker.yaml
  .github/workflows/nerdctl.yaml
  .github/workflows/podman.yml
  .github/workflows/vm.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3600 Bump containerd to v1.7.16
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3618 promote stmcginnis to reviwer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3624 set skipPhases in Init and JoinConfiguration
  pkg/cluster/internal/create/actions/kubeadminit/init.go
  pkg/cluster/internal/create/actions/kubeadmjoin/join.go
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3614 Add a new directory/remote builder - new modes to specify k8s binaries to build node-images
  pkg/build/nodeimage/build.go
  pkg/build/nodeimage/buildcontext.go
  pkg/build/nodeimage/internal/kube/builder_remote.go
  pkg/build/nodeimage/internal/kube/builder_tarball.go
  pkg/build/nodeimage/internal/kube/tar.go
  pkg/build/nodeimage/options.go
  pkg/cmd/kind/build/nodeimage/nodeimage.go
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3631 Add cgroupns requirement to known issues
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3628 Update Go dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M
