Repository kubernetes-sigs/kind, pull requests merged in 2024-04, with the labels that each got.

#3564 bump base image
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3548 bump containerd, cri-tools, CNI plugins, and containerd-fuse-overlayfs
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3335 Require go 1.17+
  .go-version
  Makefile
  go.mod
  go.sum
  hack/build/gotoolchain.sh
  hack/build/setup-go.sh
  hack/tools/.golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
  images/base/Dockerfile
  images/kindnetd/Dockerfile
  images/kindnetd/cmd/kindnetd/main.go
  images/kindnetd/go.mod
  images/local-path-provisioner/Dockerfile
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/nerdctl/provision.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/fs/fs.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, area/provider/docker, area/provider/podman

#3568 Bump containerd to 1.7.15
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3570 bump base image
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3567 Fix nerdctl create multi-node cluster fail by do not create container concurrently
  pkg/cluster/internal/providers/nerdctl/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3572 docs: add required containerd version
  site/content/docs/user/rootless.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, ok-to-test

#3577 support kube-proxy nftables mode
  pkg/apis/config/v1alpha4/types.go
  pkg/cluster/internal/kubeadm/config.go
  pkg/internal/apis/config/types.go
  pkg/internal/apis/config/validate.go
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3584 use cloud-provider-kind as recommended loadbalancer
  site/content/docs/user/loadbalancer.md
  site/content/docs/user/resources.md
  site/static/examples/loadbalancer/metallb-config.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M

#3585 fix docs
  site/content/docs/user/resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3588 Nftables be liberal with TCP
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3595 Remove redundant default type value from flag doc
  pkg/cmd/kind/build/nodeimage/nodeimage.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test
