Repository kubernetes-sigs/kind, pull requests merged in 2024-07, with the labels that each got.

#3676 Go 1.22 / deps update
  .go-version
  images/base/Dockerfile
  images/haproxy/Dockerfile
  images/local-path-helper/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3687 docs(user/rootless.md) Mention possible pids_limit issues with rootless podman
  site/content/docs/user/rootless.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3612 Kindnet network policies
  images/kindnetd/Dockerfile
  images/kindnetd/cmd/kindnetd/cni.go
  images/kindnetd/cmd/kindnetd/main.go
  images/kindnetd/cmd/kindnetd/masq.go
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3692 Fix Ingress migration guide link error
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3693 Fix Kubeadm template format
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3698 Bump kindnetd to get the fix for kube-network-policies
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/build/nodeimage/const_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/M
