Repository kubernetes-sigs/kind, pull requests merged in 2024-02, with the labels that each got.

#3497 Update runc and containerd.
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, priority/critical-urgent

#3498 use latest go 1.20 (1.20.13)
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3499 update images
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/XS, priority/critical-urgent

#3500 mark v0.21.0
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes

#3501 update install for v0.21.0
  README.md
  site/config.toml
Labels: approved, cncf-cla: yes

#3507 Remove `exclude-from-external-load-balancers` from single node clusters
  pkg/cluster/internal/create/actions/kubeadminit/init.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3509 WSL: Update package list to build image
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3480 Pass proxy environment variables to the building container when building node images
  pkg/build/nodeimage/buildcontext.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#3513 Support multiple random ExtraPortMappings
  pkg/cluster/internal/providers/common/getport.go
  pkg/cluster/internal/providers/common/getport_test.go
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provision.go
  pkg/internal/apis/config/validate.go
  pkg/internal/apis/config/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test, area/provider/docker, area/provider/podman

#3477 Avoid setting /kind/bin to 0644
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#3495 update Contour ingress docs
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3520 images: allow overriding IMAGE_NAME
  images/Makefile.common.in
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3521 bump base image
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/buildcontext.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/S

#3522 update to 1.29.2 image
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, size/XS

#3523 Mark 0.22.0 release
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, size/XS

#3524 bump docs to 0.22.0
  README.md
  site/config.toml
Labels: approved, cncf-cla: yes

#3527 Fix Podman test failures caused by kernel update
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3483 Add ipFamily validation
  pkg/internal/apis/config/validate.go
  pkg/internal/apis/config/validate_test.go
Labels: approved, cncf-cla: yes, size/S, ok-to-test

#3429 Initial provider implementation for nerdctl (+finch)
  .github/workflows/nerdctl.yaml
  pkg/cluster/internal/providers/nerdctl/OWNERS
  pkg/cluster/internal/providers/nerdctl/constants.go
  pkg/cluster/internal/providers/nerdctl/images.go
  pkg/cluster/internal/providers/nerdctl/network.go
  pkg/cluster/internal/providers/nerdctl/network_test.go
  pkg/cluster/internal/providers/nerdctl/node.go
  pkg/cluster/internal/providers/nerdctl/provider.go
  pkg/cluster/internal/providers/nerdctl/provision.go
  pkg/cluster/internal/providers/nerdctl/util.go
  pkg/cluster/provider.go
  pkg/internal/runtime/runtime.go
Labels: approved, size/XXL, cncf-cla: yes, lgtm, ok-to-test

#3532 Docs: Add docs for nerdctl support
  .github/ISSUE_TEMPLATE/bug-report.md
  README.md
  pkg/cluster/provider.go
  site/content/_index.md
  site/content/docs/contributing/development.md
  site/content/docs/user/quick-start.md
  site/content/docs/user/rootless.md
Labels: approved, cncf-cla: yes, lgtm, size/M
