Repository kubernetes-sigs/kind, pull requests merged in 2024-08, with the labels that each got.

#3690 Reword comments and fix typo in buildcontext.go
  pkg/build/nodeimage/buildcontext.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#3689 Add known issue for WSL2 and cgroupv2 support
  site/content/docs/user/images/docker-pref-2.png
  site/content/docs/user/known-issues.md
  site/content/docs/user/using-wsl2.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/L

#3702 Add powershell completion
  pkg/cmd/kind/completion/completion.go
  pkg/cmd/kind/completion/powershell/powershell.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#3707 switch to go 1.22.6
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3708 bump images following go 1.22.6 update
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3715 fix getting version from tarball
  pkg/build/nodeimage/internal/kube/builder_remote.go
  pkg/build/nodeimage/internal/kube/builder_tarball.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3718 Add CRI-O Kind tutorial to Kind user docs
  site/content/docs/user/resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3719 Update ingress.md
  site/content/docs/user/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3720 add clarifications to resources.md
  site/content/docs/user/resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3721 Add install note to rootless docs
  site/content/docs/user/rootless.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test
