Repository kubernetes-sigs/kind, pull requests merged in 2025-01, with the labels that each got.

#3841 update shellescape to latest with new vanity import
  go.mod
  go.sum
  pkg/build/nodeimage/internal/kube/source.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/logs/logs.go
  pkg/exec/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3828 update containerd to v2.0.2
  images/base/Dockerfile
  pkg/cluster/nodeutils/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3851 doc: fix typo
  site/content/docs/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3848 update to latest base image with containerd 2.0.2, ensure containerd is ready before importing images
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/buildcontext.go
  pkg/build/nodeimage/defaults.go
  pkg/build/nodeimage/imageimporter.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3573 fix: remove NoArgs positional arguments validation
  pkg/cmd/kind/build/build.go
  pkg/cmd/kind/completion/completion.go
  pkg/cmd/kind/create/create.go
  pkg/cmd/kind/delete/delete.go
  pkg/cmd/kind/export/export.go
  pkg/cmd/kind/get/get.go
  pkg/cmd/kind/root.go
  pkg/cmd/kind/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3850 test: upgrade nerdctl to v2
  .github/workflows/nerdctl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3823 fix push node having qemu setup reliably
  hack/build/init-buildx.sh
  hack/release/build/push-node.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3838 Add description to delete cluster subcommands
  pkg/cmd/kind/delete/cluster/deletecluster.go
  pkg/cmd/kind/delete/clusters/deleteclusters.go
Labels: approved, cncf-cla: yes, lgtm, size/S
