Repository kubernetes-sigs/kind, pull requests merged in 2025-02, with the labels that each got.

#3856 version test cleanup: don't mutate globals, use pre-computed expected values
  pkg/cmd/kind/version/version.go
  pkg/cmd/kind/version/version_test.go
Labels: approved, cncf-cla: yes, lgtm, kind/cleanup, size/M

#3859 Statically link CNI plugins
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3861 bump base image with statically linked plugins, improve new push-node.sh, adopt 1.32.2
  hack/release/push-node.sh
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3863 bump go to 1.23.6
  .go-version
Labels: approved, cncf-cla: yes, size/XS

#3864 bump golang images
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/const_storage.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, size/XS

#3866 mark v0.27.0
  README.md
  pkg/cmd/kind/version/version.go
  site/config.toml
Labels: approved, cncf-cla: yes, size/S

#3877 bump runc to 1.2.4
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3869 Attempt to tidy up documentation
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3872 Document KubeletConfiguration limitation
  site/content/docs/user/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#3878 bump base image to v20250228-c27ae4d9 with runc 1.2.4
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
