Repository kubernetes-sigs/kind, pull requests merged in 2025-04, with the labels that each got.

#3902 Promote stmcginnis to maintainer
  OWNERS
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3905 Update nginx controller from 1.12.0-beta.0 to 1.12.1
  site/static/examples/ingress/deploy-ingress-nginx.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#3906 migrate off of gopkg.in/yaml.v3
  go.mod
  pkg/apis/config/v1alpha4/yaml.go
  pkg/cluster/internal/kubeconfig/internal/kubeconfig/encode.go
  pkg/cluster/internal/kubeconfig/internal/kubeconfig/read.go
  pkg/internal/apis/config/encoding/load.go
  pkg/internal/patch/toml.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3919 clarify local registry address
  site/content/docs/user/local-registry.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3920 bump go, containerd, runc
  .github/workflows/docker.yaml
  .github/workflows/nerdctl.yaml
  .go-version
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3922 eliminate yaml.v3
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/installcni/cni.go
  pkg/cluster/internal/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M
