Repository kubernetes-sigs/kind, pull requests merged in 2025-05, with the labels that each got.

#3926 docs: add note about vpn cidr clashes
  site/content/docs/user/known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-ok-to-test

#3925 upgrade cni plugins, crictl
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3930 bump kindnet dependencies
  images/base/Dockerfile
  images/kindnetd/Dockerfile
  images/kindnetd/go.mod
  images/kindnetd/go.sum
  pkg/build/nodeimage/const_cni.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3935 Update default image to use v1.33.1
  pkg/apis/config/defaults/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3934 Release 028
  README.md
  pkg/cmd/kind/version/version.go
  site/config.toml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3937 upgrade containerd to 2.1.1
  images/base/Dockerfile
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3939 mark v0.29.0
  README.md
  pkg/cmd/kind/version/version.go
  site/config.toml
Labels: approved, cncf-cla: yes, size/S
