Repository kubernetes-sigs/kind, pull requests merged in 2025-03, with the labels that each got.

#3883 update runc and containerd to latest stable
  images/base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3865 bump actions runners to ubuntu 22.04, as 20.04 is deprecated
  .github/workflows/docker.yaml
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3888 podman actions fixup
  .github/workflows/podman.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3889 CI: simplify setting up Lima
  .github/workflows/vm.yaml
  hack/ci/lima-helper.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#3885 update registry docs for containerd 2.x
  site/content/docs/user/private-registries.md
  site/static/examples/kind-with-registry.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#3886 update default base, node image
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3881 fix: set global arp_ignore param for kindnet
  images/base/files/etc/sysctl.d/10-network-magic.conf
Labels: approved, cncf-cla: yes, lgtm, size/S, area/provider/docker, area/provider/podman, area/provider/nerdctl

#3890 update base with arp_ignore
  pkg/apis/config/defaults/image.go
  pkg/build/nodeimage/defaults.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3898 pin new actions to commit.
  .github/workflows/vm.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
